/*
MIT License

Copyright (c) 2022 Ryan Egesdahl

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

SPDX-FileCopyrightText: 2020 Ryan Egesdahl
SPDX-License-Identifier: MIT
*/

#include <utf/utf.h>

#include "unity.h"

void setUp(void) {}

void tearDown(void) {}

void test_isalnum(void)
{
    TEST_ASSERT_FALSE(utf_isalnum(0));    /* NUL */
    TEST_ASSERT_FALSE(utf_isalnum(1));    /* SOH */
    TEST_ASSERT_FALSE(utf_isalnum(2));    /* STX */
    TEST_ASSERT_FALSE(utf_isalnum(3));    /* ETX */
    TEST_ASSERT_FALSE(utf_isalnum(4));    /* EOT */
    TEST_ASSERT_FALSE(utf_isalnum(5));    /* ENQ */
    TEST_ASSERT_FALSE(utf_isalnum(6));    /* ACK */
    TEST_ASSERT_FALSE(utf_isalnum(7));    /* BEL */
    TEST_ASSERT_FALSE(utf_isalnum(8));    /* BS  */
    TEST_ASSERT_FALSE(utf_isalnum(9));    /* HT  */
    TEST_ASSERT_FALSE(utf_isalnum(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_isalnum(11));   /* VT  */
    TEST_ASSERT_FALSE(utf_isalnum(12));   /* FF  */
    TEST_ASSERT_FALSE(utf_isalnum(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_isalnum(14));   /* SO  */
    TEST_ASSERT_FALSE(utf_isalnum(15));   /* SI  */
    TEST_ASSERT_FALSE(utf_isalnum(16));   /* DLE */
    TEST_ASSERT_FALSE(utf_isalnum(17));   /* DC1 */
    TEST_ASSERT_FALSE(utf_isalnum(18));   /* DC2 */
    TEST_ASSERT_FALSE(utf_isalnum(19));   /* DC3 */
    TEST_ASSERT_FALSE(utf_isalnum(20));   /* DC4 */
    TEST_ASSERT_FALSE(utf_isalnum(21));   /* NAK */
    TEST_ASSERT_FALSE(utf_isalnum(22));   /* SYN */
    TEST_ASSERT_FALSE(utf_isalnum(23));   /* ETB */
    TEST_ASSERT_FALSE(utf_isalnum(24));   /* CAN */
    TEST_ASSERT_FALSE(utf_isalnum(25));   /* EM  */
    TEST_ASSERT_FALSE(utf_isalnum(26));   /* SUB */
    TEST_ASSERT_FALSE(utf_isalnum(27));   /* ESC */
    TEST_ASSERT_FALSE(utf_isalnum(28));   /* FS  */
    TEST_ASSERT_FALSE(utf_isalnum(29));   /* GS  */
    TEST_ASSERT_FALSE(utf_isalnum(30));   /* RS  */
    TEST_ASSERT_FALSE(utf_isalnum(31));   /* US  */
    TEST_ASSERT_FALSE(utf_isalnum(32));   /* SP  */
    TEST_ASSERT_FALSE(utf_isalnum(33));   /* !   */
    TEST_ASSERT_FALSE(utf_isalnum(34));   /* "   */
    TEST_ASSERT_FALSE(utf_isalnum(35));   /* #   */
    TEST_ASSERT_FALSE(utf_isalnum(36));   /* $   */
    TEST_ASSERT_FALSE(utf_isalnum(37));   /* %   */
    TEST_ASSERT_FALSE(utf_isalnum(38));   /* &   */
    TEST_ASSERT_FALSE(utf_isalnum(39));   /* '   */
    TEST_ASSERT_FALSE(utf_isalnum(40));   /* (   */
    TEST_ASSERT_FALSE(utf_isalnum(41));   /* )   */
    TEST_ASSERT_FALSE(utf_isalnum(42));   /* *   */
    TEST_ASSERT_FALSE(utf_isalnum(43));   /* +   */
    TEST_ASSERT_FALSE(utf_isalnum(44));   /* ,   */
    TEST_ASSERT_FALSE(utf_isalnum(45));   /* -   */
    TEST_ASSERT_FALSE(utf_isalnum(46));   /* .   */
    TEST_ASSERT_FALSE(utf_isalnum(47));   /* /   */
    TEST_ASSERT_TRUE(utf_isalnum(48));    /* 0   */
    TEST_ASSERT_TRUE(utf_isalnum(49));    /* 1   */
    TEST_ASSERT_TRUE(utf_isalnum(50));    /* 2   */
    TEST_ASSERT_TRUE(utf_isalnum(51));    /* 3   */
    TEST_ASSERT_TRUE(utf_isalnum(52));    /* 4   */
    TEST_ASSERT_TRUE(utf_isalnum(53));    /* 5   */
    TEST_ASSERT_TRUE(utf_isalnum(54));    /* 6   */
    TEST_ASSERT_TRUE(utf_isalnum(55));    /* 7   */
    TEST_ASSERT_TRUE(utf_isalnum(56));    /* 8   */
    TEST_ASSERT_TRUE(utf_isalnum(57));    /* 9   */
    TEST_ASSERT_FALSE(utf_isalnum(58));   /* :   */
    TEST_ASSERT_FALSE(utf_isalnum(59));   /* ;   */
    TEST_ASSERT_FALSE(utf_isalnum(60));   /* <   */
    TEST_ASSERT_FALSE(utf_isalnum(61));   /* =   */
    TEST_ASSERT_FALSE(utf_isalnum(62));   /* >   */
    TEST_ASSERT_FALSE(utf_isalnum(63));   /* ?   */
    TEST_ASSERT_FALSE(utf_isalnum(64));   /* @   */
    TEST_ASSERT_TRUE(utf_isalnum(65));    /* A   */
    TEST_ASSERT_TRUE(utf_isalnum(66));    /* B   */
    TEST_ASSERT_TRUE(utf_isalnum(67));    /* C   */
    TEST_ASSERT_TRUE(utf_isalnum(68));    /* D   */
    TEST_ASSERT_TRUE(utf_isalnum(69));    /* E   */
    TEST_ASSERT_TRUE(utf_isalnum(70));    /* F   */
    TEST_ASSERT_TRUE(utf_isalnum(71));    /* G   */
    TEST_ASSERT_TRUE(utf_isalnum(72));    /* H   */
    TEST_ASSERT_TRUE(utf_isalnum(73));    /* I   */
    TEST_ASSERT_TRUE(utf_isalnum(74));    /* J   */
    TEST_ASSERT_TRUE(utf_isalnum(75));    /* K   */
    TEST_ASSERT_TRUE(utf_isalnum(76));    /* L   */
    TEST_ASSERT_TRUE(utf_isalnum(77));    /* M   */
    TEST_ASSERT_TRUE(utf_isalnum(78));    /* N   */
    TEST_ASSERT_TRUE(utf_isalnum(79));    /* O   */
    TEST_ASSERT_TRUE(utf_isalnum(80));    /* P   */
    TEST_ASSERT_TRUE(utf_isalnum(81));    /* Q   */
    TEST_ASSERT_TRUE(utf_isalnum(82));    /* R   */
    TEST_ASSERT_TRUE(utf_isalnum(83));    /* S   */
    TEST_ASSERT_TRUE(utf_isalnum(84));    /* T   */
    TEST_ASSERT_TRUE(utf_isalnum(85));    /* U   */
    TEST_ASSERT_TRUE(utf_isalnum(86));    /* V   */
    TEST_ASSERT_TRUE(utf_isalnum(87));    /* W   */
    TEST_ASSERT_TRUE(utf_isalnum(88));    /* X   */
    TEST_ASSERT_TRUE(utf_isalnum(89));    /* Y   */
    TEST_ASSERT_TRUE(utf_isalnum(90));    /* Z   */
    TEST_ASSERT_FALSE(utf_isalnum(91));   /* [   */
    TEST_ASSERT_FALSE(utf_isalnum(92));   /* \   */
    TEST_ASSERT_FALSE(utf_isalnum(93));   /* ]   */
    TEST_ASSERT_FALSE(utf_isalnum(94));   /* ^   */
    TEST_ASSERT_FALSE(utf_isalnum(95));   /* _   */
    TEST_ASSERT_FALSE(utf_isalnum(96));   /* `   */
    TEST_ASSERT_TRUE(utf_isalnum(97));    /* a   */
    TEST_ASSERT_TRUE(utf_isalnum(98));    /* b   */
    TEST_ASSERT_TRUE(utf_isalnum(99));    /* c   */
    TEST_ASSERT_TRUE(utf_isalnum(100));   /* d   */
    TEST_ASSERT_TRUE(utf_isalnum(101));   /* e   */
    TEST_ASSERT_TRUE(utf_isalnum(102));   /* f   */
    TEST_ASSERT_TRUE(utf_isalnum(103));   /* g   */
    TEST_ASSERT_TRUE(utf_isalnum(104));   /* h   */
    TEST_ASSERT_TRUE(utf_isalnum(105));   /* i   */
    TEST_ASSERT_TRUE(utf_isalnum(106));   /* j   */
    TEST_ASSERT_TRUE(utf_isalnum(107));   /* k   */
    TEST_ASSERT_TRUE(utf_isalnum(108));   /* l   */
    TEST_ASSERT_TRUE(utf_isalnum(109));   /* m   */
    TEST_ASSERT_TRUE(utf_isalnum(110));   /* n   */
    TEST_ASSERT_TRUE(utf_isalnum(111));   /* o   */
    TEST_ASSERT_TRUE(utf_isalnum(112));   /* p   */
    TEST_ASSERT_TRUE(utf_isalnum(113));   /* q   */
    TEST_ASSERT_TRUE(utf_isalnum(114));   /* r   */
    TEST_ASSERT_TRUE(utf_isalnum(115));   /* s   */
    TEST_ASSERT_TRUE(utf_isalnum(116));   /* t   */
    TEST_ASSERT_TRUE(utf_isalnum(117));   /* u   */
    TEST_ASSERT_TRUE(utf_isalnum(118));   /* v   */
    TEST_ASSERT_TRUE(utf_isalnum(119));   /* w   */
    TEST_ASSERT_TRUE(utf_isalnum(120));   /* x   */
    TEST_ASSERT_TRUE(utf_isalnum(121));   /* y   */
    TEST_ASSERT_TRUE(utf_isalnum(122));   /* z   */
    TEST_ASSERT_FALSE(utf_isalnum(123));  /* {   */
    TEST_ASSERT_FALSE(utf_isalnum(124));  /* |   */
    TEST_ASSERT_FALSE(utf_isalnum(125));  /* }   */
    TEST_ASSERT_FALSE(utf_isalnum(126));  /* ~   */
    TEST_ASSERT_FALSE(utf_isalnum(127));  /* DEL */
    TEST_ASSERT_FALSE(utf_isalnum(178));  /* ²   */
}

void test_isalpha(void)
{
    TEST_ASSERT_FALSE(utf_isalpha(0));    /* NUL */
    TEST_ASSERT_FALSE(utf_isalpha(1));    /* SOH */
    TEST_ASSERT_FALSE(utf_isalpha(2));    /* STX */
    TEST_ASSERT_FALSE(utf_isalpha(3));    /* ETX */
    TEST_ASSERT_FALSE(utf_isalpha(4));    /* EOT */
    TEST_ASSERT_FALSE(utf_isalpha(5));    /* ENQ */
    TEST_ASSERT_FALSE(utf_isalpha(6));    /* ACK */
    TEST_ASSERT_FALSE(utf_isalpha(7));    /* BEL */
    TEST_ASSERT_FALSE(utf_isalpha(8));    /* BS  */
    TEST_ASSERT_FALSE(utf_isalpha(9));    /* HT  */
    TEST_ASSERT_FALSE(utf_isalpha(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_isalpha(11));   /* VT  */
    TEST_ASSERT_FALSE(utf_isalpha(12));   /* FF  */
    TEST_ASSERT_FALSE(utf_isalpha(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_isalpha(14));   /* SO  */
    TEST_ASSERT_FALSE(utf_isalpha(15));   /* SI  */
    TEST_ASSERT_FALSE(utf_isalpha(16));   /* DLE */
    TEST_ASSERT_FALSE(utf_isalpha(17));   /* DC1 */
    TEST_ASSERT_FALSE(utf_isalpha(18));   /* DC2 */
    TEST_ASSERT_FALSE(utf_isalpha(19));   /* DC3 */
    TEST_ASSERT_FALSE(utf_isalpha(20));   /* DC4 */
    TEST_ASSERT_FALSE(utf_isalpha(21));   /* NAK */
    TEST_ASSERT_FALSE(utf_isalpha(22));   /* SYN */
    TEST_ASSERT_FALSE(utf_isalpha(23));   /* ETB */
    TEST_ASSERT_FALSE(utf_isalpha(24));   /* CAN */
    TEST_ASSERT_FALSE(utf_isalpha(25));   /* EM  */
    TEST_ASSERT_FALSE(utf_isalpha(26));   /* SUB */
    TEST_ASSERT_FALSE(utf_isalpha(27));   /* ESC */
    TEST_ASSERT_FALSE(utf_isalpha(28));   /* FS  */
    TEST_ASSERT_FALSE(utf_isalpha(29));   /* GS  */
    TEST_ASSERT_FALSE(utf_isalpha(30));   /* RS  */
    TEST_ASSERT_FALSE(utf_isalpha(31));   /* US  */
    TEST_ASSERT_FALSE(utf_isalpha(32));   /* SP  */
    TEST_ASSERT_FALSE(utf_isalpha(33));   /* !   */
    TEST_ASSERT_FALSE(utf_isalpha(34));   /* "   */
    TEST_ASSERT_FALSE(utf_isalpha(35));   /* #   */
    TEST_ASSERT_FALSE(utf_isalpha(36));   /* $   */
    TEST_ASSERT_FALSE(utf_isalpha(37));   /* %   */
    TEST_ASSERT_FALSE(utf_isalpha(38));   /* &   */
    TEST_ASSERT_FALSE(utf_isalpha(39));   /* '   */
    TEST_ASSERT_FALSE(utf_isalpha(40));   /* (   */
    TEST_ASSERT_FALSE(utf_isalpha(41));   /* )   */
    TEST_ASSERT_FALSE(utf_isalpha(42));   /* *   */
    TEST_ASSERT_FALSE(utf_isalpha(43));   /* +   */
    TEST_ASSERT_FALSE(utf_isalpha(44));   /* ,   */
    TEST_ASSERT_FALSE(utf_isalpha(45));   /* -   */
    TEST_ASSERT_FALSE(utf_isalpha(46));   /* .   */
    TEST_ASSERT_FALSE(utf_isalpha(47));   /* /   */
    TEST_ASSERT_FALSE(utf_isalpha(48));   /* 0   */
    TEST_ASSERT_FALSE(utf_isalpha(49));   /* 1   */
    TEST_ASSERT_FALSE(utf_isalpha(50));   /* 2   */
    TEST_ASSERT_FALSE(utf_isalpha(51));   /* 3   */
    TEST_ASSERT_FALSE(utf_isalpha(52));   /* 4   */
    TEST_ASSERT_FALSE(utf_isalpha(53));   /* 5   */
    TEST_ASSERT_FALSE(utf_isalpha(54));   /* 6   */
    TEST_ASSERT_FALSE(utf_isalpha(55));   /* 7   */
    TEST_ASSERT_FALSE(utf_isalpha(56));   /* 8   */
    TEST_ASSERT_FALSE(utf_isalpha(57));   /* 9   */
    TEST_ASSERT_FALSE(utf_isalpha(58));   /* :   */
    TEST_ASSERT_FALSE(utf_isalpha(59));   /* ;   */
    TEST_ASSERT_FALSE(utf_isalpha(60));   /* <   */
    TEST_ASSERT_FALSE(utf_isalpha(61));   /* =   */
    TEST_ASSERT_FALSE(utf_isalpha(62));   /* >   */
    TEST_ASSERT_FALSE(utf_isalpha(63));   /* ?   */
    TEST_ASSERT_FALSE(utf_isalpha(64));   /* @   */
    TEST_ASSERT_TRUE(utf_isalpha(65));    /* A   */
    TEST_ASSERT_TRUE(utf_isalpha(66));    /* B   */
    TEST_ASSERT_TRUE(utf_isalpha(67));    /* C   */
    TEST_ASSERT_TRUE(utf_isalpha(68));    /* D   */
    TEST_ASSERT_TRUE(utf_isalpha(69));    /* E   */
    TEST_ASSERT_TRUE(utf_isalpha(70));    /* F   */
    TEST_ASSERT_TRUE(utf_isalpha(71));    /* G   */
    TEST_ASSERT_TRUE(utf_isalpha(72));    /* H   */
    TEST_ASSERT_TRUE(utf_isalpha(73));    /* I   */
    TEST_ASSERT_TRUE(utf_isalpha(74));    /* J   */
    TEST_ASSERT_TRUE(utf_isalpha(75));    /* K   */
    TEST_ASSERT_TRUE(utf_isalpha(76));    /* L   */
    TEST_ASSERT_TRUE(utf_isalpha(77));    /* M   */
    TEST_ASSERT_TRUE(utf_isalpha(78));    /* N   */
    TEST_ASSERT_TRUE(utf_isalpha(79));    /* O   */
    TEST_ASSERT_TRUE(utf_isalpha(80));    /* P   */
    TEST_ASSERT_TRUE(utf_isalpha(81));    /* Q   */
    TEST_ASSERT_TRUE(utf_isalpha(82));    /* R   */
    TEST_ASSERT_TRUE(utf_isalpha(83));    /* S   */
    TEST_ASSERT_TRUE(utf_isalpha(84));    /* T   */
    TEST_ASSERT_TRUE(utf_isalpha(85));    /* U   */
    TEST_ASSERT_TRUE(utf_isalpha(86));    /* V   */
    TEST_ASSERT_TRUE(utf_isalpha(87));    /* W   */
    TEST_ASSERT_TRUE(utf_isalpha(88));    /* X   */
    TEST_ASSERT_TRUE(utf_isalpha(89));    /* Y   */
    TEST_ASSERT_TRUE(utf_isalpha(90));    /* Z   */
    TEST_ASSERT_FALSE(utf_isalpha(91));   /* [   */
    TEST_ASSERT_FALSE(utf_isalpha(92));   /* \   */
    TEST_ASSERT_FALSE(utf_isalpha(93));   /* ]   */
    TEST_ASSERT_FALSE(utf_isalpha(94));   /* ^   */
    TEST_ASSERT_FALSE(utf_isalpha(95));   /* _   */
    TEST_ASSERT_FALSE(utf_isalpha(96));   /* `   */
    TEST_ASSERT_TRUE(utf_isalpha(97));    /* a   */
    TEST_ASSERT_TRUE(utf_isalpha(98));    /* b   */
    TEST_ASSERT_TRUE(utf_isalpha(99));    /* c   */
    TEST_ASSERT_TRUE(utf_isalpha(100));   /* d   */
    TEST_ASSERT_TRUE(utf_isalpha(101));   /* e   */
    TEST_ASSERT_TRUE(utf_isalpha(102));   /* f   */
    TEST_ASSERT_TRUE(utf_isalpha(103));   /* g   */
    TEST_ASSERT_TRUE(utf_isalpha(104));   /* h   */
    TEST_ASSERT_TRUE(utf_isalpha(105));   /* i   */
    TEST_ASSERT_TRUE(utf_isalpha(106));   /* j   */
    TEST_ASSERT_TRUE(utf_isalpha(107));   /* k   */
    TEST_ASSERT_TRUE(utf_isalpha(108));   /* l   */
    TEST_ASSERT_TRUE(utf_isalpha(109));   /* m   */
    TEST_ASSERT_TRUE(utf_isalpha(110));   /* n   */
    TEST_ASSERT_TRUE(utf_isalpha(111));   /* o   */
    TEST_ASSERT_TRUE(utf_isalpha(112));   /* p   */
    TEST_ASSERT_TRUE(utf_isalpha(113));   /* q   */
    TEST_ASSERT_TRUE(utf_isalpha(114));   /* r   */
    TEST_ASSERT_TRUE(utf_isalpha(115));   /* s   */
    TEST_ASSERT_TRUE(utf_isalpha(116));   /* t   */
    TEST_ASSERT_TRUE(utf_isalpha(117));   /* u   */
    TEST_ASSERT_TRUE(utf_isalpha(118));   /* v   */
    TEST_ASSERT_TRUE(utf_isalpha(119));   /* w   */
    TEST_ASSERT_TRUE(utf_isalpha(120));   /* x   */
    TEST_ASSERT_TRUE(utf_isalpha(121));   /* y   */
    TEST_ASSERT_TRUE(utf_isalpha(122));   /* z   */
    TEST_ASSERT_FALSE(utf_isalpha(123));  /* {   */
    TEST_ASSERT_FALSE(utf_isalpha(124));  /* |   */
    TEST_ASSERT_FALSE(utf_isalpha(125));  /* }   */
    TEST_ASSERT_FALSE(utf_isalpha(126));  /* ~   */
    TEST_ASSERT_FALSE(utf_isalpha(127));  /* DEL */
    TEST_ASSERT_FALSE(utf_isalpha(178));  /* ²   */
}

void test_iscntrl(void)
{
    TEST_ASSERT_TRUE(utf_iscntrl(0));    /* NUL */
    TEST_ASSERT_TRUE(utf_iscntrl(1));    /* SOH */
    TEST_ASSERT_TRUE(utf_iscntrl(2));    /* STX */
    TEST_ASSERT_TRUE(utf_iscntrl(3));    /* ETX */
    TEST_ASSERT_TRUE(utf_iscntrl(4));    /* EOT */
    TEST_ASSERT_TRUE(utf_iscntrl(5));    /* ENQ */
    TEST_ASSERT_TRUE(utf_iscntrl(6));    /* ACK */
    TEST_ASSERT_TRUE(utf_iscntrl(7));    /* BEL */
    TEST_ASSERT_TRUE(utf_iscntrl(8));    /* BS  */
    TEST_ASSERT_TRUE(utf_iscntrl(9));    /* HT  */
    TEST_ASSERT_TRUE(utf_iscntrl(10));   /* CR  */
    TEST_ASSERT_TRUE(utf_iscntrl(11));   /* VT  */
    TEST_ASSERT_TRUE(utf_iscntrl(12));   /* FF  */
    TEST_ASSERT_TRUE(utf_iscntrl(13));   /* LF  */
    TEST_ASSERT_TRUE(utf_iscntrl(14));   /* SO  */
    TEST_ASSERT_TRUE(utf_iscntrl(15));   /* SI  */
    TEST_ASSERT_TRUE(utf_iscntrl(16));   /* DLE */
    TEST_ASSERT_TRUE(utf_iscntrl(17));   /* DC1 */
    TEST_ASSERT_TRUE(utf_iscntrl(18));   /* DC2 */
    TEST_ASSERT_TRUE(utf_iscntrl(19));   /* DC3 */
    TEST_ASSERT_TRUE(utf_iscntrl(20));   /* DC4 */
    TEST_ASSERT_TRUE(utf_iscntrl(21));   /* NAK */
    TEST_ASSERT_TRUE(utf_iscntrl(22));   /* SYN */
    TEST_ASSERT_TRUE(utf_iscntrl(23));   /* ETB */
    TEST_ASSERT_TRUE(utf_iscntrl(24));   /* CAN */
    TEST_ASSERT_TRUE(utf_iscntrl(25));   /* EM  */
    TEST_ASSERT_TRUE(utf_iscntrl(26));   /* SUB */
    TEST_ASSERT_TRUE(utf_iscntrl(27));   /* ESC */
    TEST_ASSERT_TRUE(utf_iscntrl(28));   /* FS  */
    TEST_ASSERT_TRUE(utf_iscntrl(29));   /* GS  */
    TEST_ASSERT_TRUE(utf_iscntrl(30));   /* RS  */
    TEST_ASSERT_TRUE(utf_iscntrl(31));   /* US  */
    TEST_ASSERT_FALSE(utf_iscntrl(32));  /* SP  */
    TEST_ASSERT_FALSE(utf_iscntrl(33));  /* !   */
    TEST_ASSERT_FALSE(utf_iscntrl(34));  /* "   */
    TEST_ASSERT_FALSE(utf_iscntrl(35));  /* #   */
    TEST_ASSERT_FALSE(utf_iscntrl(36));  /* $   */
    TEST_ASSERT_FALSE(utf_iscntrl(37));  /* %   */
    TEST_ASSERT_FALSE(utf_iscntrl(38));  /* &   */
    TEST_ASSERT_FALSE(utf_iscntrl(39));  /* '   */
    TEST_ASSERT_FALSE(utf_iscntrl(40));  /* (   */
    TEST_ASSERT_FALSE(utf_iscntrl(41));  /* )   */
    TEST_ASSERT_FALSE(utf_iscntrl(42));  /* *   */
    TEST_ASSERT_FALSE(utf_iscntrl(43));  /* +   */
    TEST_ASSERT_FALSE(utf_iscntrl(44));  /* ,   */
    TEST_ASSERT_FALSE(utf_iscntrl(45));  /* -   */
    TEST_ASSERT_FALSE(utf_iscntrl(46));  /* .   */
    TEST_ASSERT_FALSE(utf_iscntrl(47));  /* /   */
    TEST_ASSERT_FALSE(utf_iscntrl(48));  /* 0   */
    TEST_ASSERT_FALSE(utf_iscntrl(49));  /* 1   */
    TEST_ASSERT_FALSE(utf_iscntrl(50));  /* 2   */
    TEST_ASSERT_FALSE(utf_iscntrl(51));  /* 3   */
    TEST_ASSERT_FALSE(utf_iscntrl(52));  /* 4   */
    TEST_ASSERT_FALSE(utf_iscntrl(53));  /* 5   */
    TEST_ASSERT_FALSE(utf_iscntrl(54));  /* 6   */
    TEST_ASSERT_FALSE(utf_iscntrl(55));  /* 7   */
    TEST_ASSERT_FALSE(utf_iscntrl(56));  /* 8   */
    TEST_ASSERT_FALSE(utf_iscntrl(57));  /* 9   */
    TEST_ASSERT_FALSE(utf_iscntrl(58));  /* :   */
    TEST_ASSERT_FALSE(utf_iscntrl(59));  /* ;   */
    TEST_ASSERT_FALSE(utf_iscntrl(60));  /* <   */
    TEST_ASSERT_FALSE(utf_iscntrl(61));  /* =   */
    TEST_ASSERT_FALSE(utf_iscntrl(62));  /* >   */
    TEST_ASSERT_FALSE(utf_iscntrl(63));  /* ?   */
    TEST_ASSERT_FALSE(utf_iscntrl(64));  /* @   */
    TEST_ASSERT_FALSE(utf_iscntrl(65));  /* A   */
    TEST_ASSERT_FALSE(utf_iscntrl(66));  /* B   */
    TEST_ASSERT_FALSE(utf_iscntrl(67));  /* C   */
    TEST_ASSERT_FALSE(utf_iscntrl(68));  /* D   */
    TEST_ASSERT_FALSE(utf_iscntrl(69));  /* E   */
    TEST_ASSERT_FALSE(utf_iscntrl(70));  /* F   */
    TEST_ASSERT_FALSE(utf_iscntrl(71));  /* G   */
    TEST_ASSERT_FALSE(utf_iscntrl(72));  /* H   */
    TEST_ASSERT_FALSE(utf_iscntrl(73));  /* I   */
    TEST_ASSERT_FALSE(utf_iscntrl(74));  /* J   */
    TEST_ASSERT_FALSE(utf_iscntrl(75));  /* K   */
    TEST_ASSERT_FALSE(utf_iscntrl(76));  /* L   */
    TEST_ASSERT_FALSE(utf_iscntrl(77));  /* M   */
    TEST_ASSERT_FALSE(utf_iscntrl(78));  /* N   */
    TEST_ASSERT_FALSE(utf_iscntrl(79));  /* O   */
    TEST_ASSERT_FALSE(utf_iscntrl(80));  /* P   */
    TEST_ASSERT_FALSE(utf_iscntrl(81));  /* Q   */
    TEST_ASSERT_FALSE(utf_iscntrl(82));  /* R   */
    TEST_ASSERT_FALSE(utf_iscntrl(83));  /* S   */
    TEST_ASSERT_FALSE(utf_iscntrl(84));  /* T   */
    TEST_ASSERT_FALSE(utf_iscntrl(85));  /* U   */
    TEST_ASSERT_FALSE(utf_iscntrl(86));  /* V   */
    TEST_ASSERT_FALSE(utf_iscntrl(87));  /* W   */
    TEST_ASSERT_FALSE(utf_iscntrl(88));  /* X   */
    TEST_ASSERT_FALSE(utf_iscntrl(89));  /* Y   */
    TEST_ASSERT_FALSE(utf_iscntrl(90));  /* Z   */
    TEST_ASSERT_FALSE(utf_iscntrl(91));  /* [   */
    TEST_ASSERT_FALSE(utf_iscntrl(92));  /* \   */
    TEST_ASSERT_FALSE(utf_iscntrl(93));  /* ]   */
    TEST_ASSERT_FALSE(utf_iscntrl(94));  /* ^   */
    TEST_ASSERT_FALSE(utf_iscntrl(95));  /* _   */
    TEST_ASSERT_FALSE(utf_iscntrl(96));  /* `   */
    TEST_ASSERT_FALSE(utf_iscntrl(97));  /* a   */
    TEST_ASSERT_FALSE(utf_iscntrl(98));  /* b   */
    TEST_ASSERT_FALSE(utf_iscntrl(99));  /* c   */
    TEST_ASSERT_FALSE(utf_iscntrl(100)); /* d   */
    TEST_ASSERT_FALSE(utf_iscntrl(101)); /* e   */
    TEST_ASSERT_FALSE(utf_iscntrl(102)); /* f   */
    TEST_ASSERT_FALSE(utf_iscntrl(103)); /* g   */
    TEST_ASSERT_FALSE(utf_iscntrl(104)); /* h   */
    TEST_ASSERT_FALSE(utf_iscntrl(105)); /* i   */
    TEST_ASSERT_FALSE(utf_iscntrl(106)); /* j   */
    TEST_ASSERT_FALSE(utf_iscntrl(107)); /* k   */
    TEST_ASSERT_FALSE(utf_iscntrl(108)); /* l   */
    TEST_ASSERT_FALSE(utf_iscntrl(109)); /* m   */
    TEST_ASSERT_FALSE(utf_iscntrl(110)); /* n   */
    TEST_ASSERT_FALSE(utf_iscntrl(111)); /* o   */
    TEST_ASSERT_FALSE(utf_iscntrl(112)); /* p   */
    TEST_ASSERT_FALSE(utf_iscntrl(113)); /* q   */
    TEST_ASSERT_FALSE(utf_iscntrl(114)); /* r   */
    TEST_ASSERT_FALSE(utf_iscntrl(115)); /* s   */
    TEST_ASSERT_FALSE(utf_iscntrl(116)); /* t   */
    TEST_ASSERT_FALSE(utf_iscntrl(117)); /* u   */
    TEST_ASSERT_FALSE(utf_iscntrl(118)); /* v   */
    TEST_ASSERT_FALSE(utf_iscntrl(119)); /* w   */
    TEST_ASSERT_FALSE(utf_iscntrl(120)); /* x   */
    TEST_ASSERT_FALSE(utf_iscntrl(121)); /* y   */
    TEST_ASSERT_FALSE(utf_iscntrl(122)); /* z   */
    TEST_ASSERT_FALSE(utf_iscntrl(123)); /* {   */
    TEST_ASSERT_FALSE(utf_iscntrl(124)); /* |   */
    TEST_ASSERT_FALSE(utf_iscntrl(125)); /* }   */
    TEST_ASSERT_FALSE(utf_iscntrl(126)); /* ~   */
    TEST_ASSERT_TRUE(utf_iscntrl(127));  /* DEL */
    TEST_ASSERT_FALSE(utf_iscntrl(178)); /* ²   */
}

void test_isdigit(void)
{
    TEST_ASSERT_FALSE(utf_isdigit(0));     /* NUL */
    TEST_ASSERT_FALSE(utf_isdigit(1));     /* SOH */
    TEST_ASSERT_FALSE(utf_isdigit(2));     /* STX */
    TEST_ASSERT_FALSE(utf_isdigit(3));     /* ETX */
    TEST_ASSERT_FALSE(utf_isdigit(4));     /* EOT */
    TEST_ASSERT_FALSE(utf_isdigit(5));     /* ENQ */
    TEST_ASSERT_FALSE(utf_isdigit(6));     /* ACK */
    TEST_ASSERT_FALSE(utf_isdigit(7));     /* BEL */
    TEST_ASSERT_FALSE(utf_isdigit(8));     /* BS  */
    TEST_ASSERT_FALSE(utf_isdigit(9));     /* HT  */
    TEST_ASSERT_FALSE(utf_isdigit(10));    /* CR  */
    TEST_ASSERT_FALSE(utf_isdigit(11));    /* VT  */
    TEST_ASSERT_FALSE(utf_isdigit(12));    /* FF  */
    TEST_ASSERT_FALSE(utf_isdigit(13));    /* LF  */
    TEST_ASSERT_FALSE(utf_isdigit(14));    /* SO  */
    TEST_ASSERT_FALSE(utf_isdigit(15));    /* SI  */
    TEST_ASSERT_FALSE(utf_isdigit(16));    /* DLE */
    TEST_ASSERT_FALSE(utf_isdigit(17));    /* DC1 */
    TEST_ASSERT_FALSE(utf_isdigit(18));    /* DC2 */
    TEST_ASSERT_FALSE(utf_isdigit(19));    /* DC3 */
    TEST_ASSERT_FALSE(utf_isdigit(20));    /* DC4 */
    TEST_ASSERT_FALSE(utf_isdigit(21));    /* NAK */
    TEST_ASSERT_FALSE(utf_isdigit(22));    /* SYN */
    TEST_ASSERT_FALSE(utf_isdigit(23));    /* ETB */
    TEST_ASSERT_FALSE(utf_isdigit(24));    /* CAN */
    TEST_ASSERT_FALSE(utf_isdigit(25));    /* EM  */
    TEST_ASSERT_FALSE(utf_isdigit(26));    /* SUB */
    TEST_ASSERT_FALSE(utf_isdigit(27));    /* ESC */
    TEST_ASSERT_FALSE(utf_isdigit(28));    /* FS  */
    TEST_ASSERT_FALSE(utf_isdigit(29));    /* GS  */
    TEST_ASSERT_FALSE(utf_isdigit(30));    /* RS  */
    TEST_ASSERT_FALSE(utf_isdigit(31));    /* US  */
    TEST_ASSERT_FALSE(utf_isdigit(32));    /* SP  */
    TEST_ASSERT_FALSE(utf_isdigit(33));    /* !   */
    TEST_ASSERT_FALSE(utf_isdigit(34));    /* "   */
    TEST_ASSERT_FALSE(utf_isdigit(35));    /* #   */
    TEST_ASSERT_FALSE(utf_isdigit(36));    /* $   */
    TEST_ASSERT_FALSE(utf_isdigit(37));    /* %   */
    TEST_ASSERT_FALSE(utf_isdigit(38));    /* &   */
    TEST_ASSERT_FALSE(utf_isdigit(39));    /* '   */
    TEST_ASSERT_FALSE(utf_isdigit(40));    /* (   */
    TEST_ASSERT_FALSE(utf_isdigit(41));    /* )   */
    TEST_ASSERT_FALSE(utf_isdigit(42));    /* *   */
    TEST_ASSERT_FALSE(utf_isdigit(43));    /* +   */
    TEST_ASSERT_FALSE(utf_isdigit(44));    /* ,   */
    TEST_ASSERT_FALSE(utf_isdigit(45));    /* -   */
    TEST_ASSERT_FALSE(utf_isdigit(46));    /* .   */
    TEST_ASSERT_FALSE(utf_isdigit(47));    /* /   */
    TEST_ASSERT_TRUE(utf_isdigit(48));     /* 0   */
    TEST_ASSERT_TRUE(utf_isdigit(49));     /* 1   */
    TEST_ASSERT_TRUE(utf_isdigit(50));     /* 2   */
    TEST_ASSERT_TRUE(utf_isdigit(51));     /* 3   */
    TEST_ASSERT_TRUE(utf_isdigit(52));     /* 4   */
    TEST_ASSERT_TRUE(utf_isdigit(53));     /* 5   */
    TEST_ASSERT_TRUE(utf_isdigit(54));     /* 6   */
    TEST_ASSERT_TRUE(utf_isdigit(55));     /* 7   */
    TEST_ASSERT_TRUE(utf_isdigit(56));     /* 8   */
    TEST_ASSERT_TRUE(utf_isdigit(57));     /* 9   */
    TEST_ASSERT_FALSE(utf_isdigit(58));    /* :   */
    TEST_ASSERT_FALSE(utf_isdigit(59));    /* ;   */
    TEST_ASSERT_FALSE(utf_isdigit(60));    /* <   */
    TEST_ASSERT_FALSE(utf_isdigit(61));    /* =   */
    TEST_ASSERT_FALSE(utf_isdigit(62));    /* >   */
    TEST_ASSERT_FALSE(utf_isdigit(63));    /* ?   */
    TEST_ASSERT_FALSE(utf_isdigit(64));    /* @   */
    TEST_ASSERT_FALSE(utf_isdigit(65));    /* A   */
    TEST_ASSERT_FALSE(utf_isdigit(66));    /* B   */
    TEST_ASSERT_FALSE(utf_isdigit(67));    /* C   */
    TEST_ASSERT_FALSE(utf_isdigit(68));    /* D   */
    TEST_ASSERT_FALSE(utf_isdigit(69));    /* E   */
    TEST_ASSERT_FALSE(utf_isdigit(70));    /* F   */
    TEST_ASSERT_FALSE(utf_isdigit(71));    /* G   */
    TEST_ASSERT_FALSE(utf_isdigit(72));    /* H   */
    TEST_ASSERT_FALSE(utf_isdigit(73));    /* I   */
    TEST_ASSERT_FALSE(utf_isdigit(74));    /* J   */
    TEST_ASSERT_FALSE(utf_isdigit(75));    /* K   */
    TEST_ASSERT_FALSE(utf_isdigit(76));    /* L   */
    TEST_ASSERT_FALSE(utf_isdigit(77));    /* M   */
    TEST_ASSERT_FALSE(utf_isdigit(78));    /* N   */
    TEST_ASSERT_FALSE(utf_isdigit(79));    /* O   */
    TEST_ASSERT_FALSE(utf_isdigit(80));    /* P   */
    TEST_ASSERT_FALSE(utf_isdigit(81));    /* Q   */
    TEST_ASSERT_FALSE(utf_isdigit(82));    /* R   */
    TEST_ASSERT_FALSE(utf_isdigit(83));    /* S   */
    TEST_ASSERT_FALSE(utf_isdigit(84));    /* T   */
    TEST_ASSERT_FALSE(utf_isdigit(85));    /* U   */
    TEST_ASSERT_FALSE(utf_isdigit(86));    /* V   */
    TEST_ASSERT_FALSE(utf_isdigit(87));    /* W   */
    TEST_ASSERT_FALSE(utf_isdigit(88));    /* X   */
    TEST_ASSERT_FALSE(utf_isdigit(89));    /* Y   */
    TEST_ASSERT_FALSE(utf_isdigit(90));    /* Z   */
    TEST_ASSERT_FALSE(utf_isdigit(91));    /* [   */
    TEST_ASSERT_FALSE(utf_isdigit(92));    /* \   */
    TEST_ASSERT_FALSE(utf_isdigit(93));    /* ]   */
    TEST_ASSERT_FALSE(utf_isdigit(94));    /* ^   */
    TEST_ASSERT_FALSE(utf_isdigit(95));    /* _   */
    TEST_ASSERT_FALSE(utf_isdigit(96));    /* `   */
    TEST_ASSERT_FALSE(utf_isdigit(97));    /* a   */
    TEST_ASSERT_FALSE(utf_isdigit(98));    /* b   */
    TEST_ASSERT_FALSE(utf_isdigit(99));    /* c   */
    TEST_ASSERT_FALSE(utf_isdigit(100));   /* d   */
    TEST_ASSERT_FALSE(utf_isdigit(101));   /* e   */
    TEST_ASSERT_FALSE(utf_isdigit(102));   /* f   */
    TEST_ASSERT_FALSE(utf_isdigit(103));   /* g   */
    TEST_ASSERT_FALSE(utf_isdigit(104));   /* h   */
    TEST_ASSERT_FALSE(utf_isdigit(105));   /* i   */
    TEST_ASSERT_FALSE(utf_isdigit(106));   /* j   */
    TEST_ASSERT_FALSE(utf_isdigit(107));   /* k   */
    TEST_ASSERT_FALSE(utf_isdigit(108));   /* l   */
    TEST_ASSERT_FALSE(utf_isdigit(109));   /* m   */
    TEST_ASSERT_FALSE(utf_isdigit(110));   /* n   */
    TEST_ASSERT_FALSE(utf_isdigit(111));   /* o   */
    TEST_ASSERT_FALSE(utf_isdigit(112));   /* p   */
    TEST_ASSERT_FALSE(utf_isdigit(113));   /* q   */
    TEST_ASSERT_FALSE(utf_isdigit(114));   /* r   */
    TEST_ASSERT_FALSE(utf_isdigit(115));   /* s   */
    TEST_ASSERT_FALSE(utf_isdigit(116));   /* t   */
    TEST_ASSERT_FALSE(utf_isdigit(117));   /* u   */
    TEST_ASSERT_FALSE(utf_isdigit(118));   /* v   */
    TEST_ASSERT_FALSE(utf_isdigit(119));   /* w   */
    TEST_ASSERT_FALSE(utf_isdigit(120));   /* x   */
    TEST_ASSERT_FALSE(utf_isdigit(121));   /* y   */
    TEST_ASSERT_FALSE(utf_isdigit(122));   /* z   */
    TEST_ASSERT_FALSE(utf_isdigit(123));   /* {   */
    TEST_ASSERT_FALSE(utf_isdigit(124));   /* |   */
    TEST_ASSERT_FALSE(utf_isdigit(125));   /* }   */
    TEST_ASSERT_FALSE(utf_isdigit(126));   /* ~   */
    TEST_ASSERT_FALSE(utf_isdigit(127));   /* DEL */
    TEST_ASSERT_FALSE(utf_isdigit(178));   /* ²   */
    TEST_ASSERT_FALSE(utf_isdigit(8528));  /* ⅐  */
}

void test_isnumber(void)
{
    TEST_ASSERT_FALSE(utf_isnumber(0));    /* NUL */
    TEST_ASSERT_FALSE(utf_isnumber(1));    /* SOH */
    TEST_ASSERT_FALSE(utf_isnumber(2));    /* STX */
    TEST_ASSERT_FALSE(utf_isnumber(3));    /* ETX */
    TEST_ASSERT_FALSE(utf_isnumber(4));    /* EOT */
    TEST_ASSERT_FALSE(utf_isnumber(5));    /* ENQ */
    TEST_ASSERT_FALSE(utf_isnumber(6));    /* ACK */
    TEST_ASSERT_FALSE(utf_isnumber(7));    /* BEL */
    TEST_ASSERT_FALSE(utf_isnumber(8));    /* BS  */
    TEST_ASSERT_FALSE(utf_isnumber(9));    /* HT  */
    TEST_ASSERT_FALSE(utf_isnumber(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_isnumber(11));   /* VT  */
    TEST_ASSERT_FALSE(utf_isnumber(12));   /* FF  */
    TEST_ASSERT_FALSE(utf_isnumber(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_isnumber(14));   /* SO  */
    TEST_ASSERT_FALSE(utf_isnumber(15));   /* SI  */
    TEST_ASSERT_FALSE(utf_isnumber(16));   /* DLE */
    TEST_ASSERT_FALSE(utf_isnumber(17));   /* DC1 */
    TEST_ASSERT_FALSE(utf_isnumber(18));   /* DC2 */
    TEST_ASSERT_FALSE(utf_isnumber(19));   /* DC3 */
    TEST_ASSERT_FALSE(utf_isnumber(20));   /* DC4 */
    TEST_ASSERT_FALSE(utf_isnumber(21));   /* NAK */
    TEST_ASSERT_FALSE(utf_isnumber(22));   /* SYN */
    TEST_ASSERT_FALSE(utf_isnumber(23));   /* ETB */
    TEST_ASSERT_FALSE(utf_isnumber(24));   /* CAN */
    TEST_ASSERT_FALSE(utf_isnumber(25));   /* EM  */
    TEST_ASSERT_FALSE(utf_isnumber(26));   /* SUB */
    TEST_ASSERT_FALSE(utf_isnumber(27));   /* ESC */
    TEST_ASSERT_FALSE(utf_isnumber(28));   /* FS  */
    TEST_ASSERT_FALSE(utf_isnumber(29));   /* GS  */
    TEST_ASSERT_FALSE(utf_isnumber(30));   /* RS  */
    TEST_ASSERT_FALSE(utf_isnumber(31));   /* US  */
    TEST_ASSERT_FALSE(utf_isnumber(32));   /* SP  */
    TEST_ASSERT_FALSE(utf_isnumber(33));   /* !   */
    TEST_ASSERT_FALSE(utf_isnumber(34));   /* "   */
    TEST_ASSERT_FALSE(utf_isnumber(35));   /* #   */
    TEST_ASSERT_FALSE(utf_isnumber(36));   /* $   */
    TEST_ASSERT_FALSE(utf_isnumber(37));   /* %   */
    TEST_ASSERT_FALSE(utf_isnumber(38));   /* &   */
    TEST_ASSERT_FALSE(utf_isnumber(39));   /* '   */
    TEST_ASSERT_FALSE(utf_isnumber(40));   /* (   */
    TEST_ASSERT_FALSE(utf_isnumber(41));   /* )   */
    TEST_ASSERT_FALSE(utf_isnumber(42));   /* *   */
    TEST_ASSERT_FALSE(utf_isnumber(43));   /* +   */
    TEST_ASSERT_FALSE(utf_isnumber(44));   /* ,   */
    TEST_ASSERT_FALSE(utf_isnumber(45));   /* -   */
    TEST_ASSERT_FALSE(utf_isnumber(46));   /* .   */
    TEST_ASSERT_FALSE(utf_isnumber(47));   /* /   */
    TEST_ASSERT_TRUE(utf_isnumber(48));    /* 0   */
    TEST_ASSERT_TRUE(utf_isnumber(49));    /* 1   */
    TEST_ASSERT_TRUE(utf_isnumber(50));    /* 2   */
    TEST_ASSERT_TRUE(utf_isnumber(51));    /* 3   */
    TEST_ASSERT_TRUE(utf_isnumber(52));    /* 4   */
    TEST_ASSERT_TRUE(utf_isnumber(53));    /* 5   */
    TEST_ASSERT_TRUE(utf_isnumber(54));    /* 6   */
    TEST_ASSERT_TRUE(utf_isnumber(55));    /* 7   */
    TEST_ASSERT_TRUE(utf_isnumber(56));    /* 8   */
    TEST_ASSERT_TRUE(utf_isnumber(57));    /* 9   */
    TEST_ASSERT_FALSE(utf_isnumber(58));   /* :   */
    TEST_ASSERT_FALSE(utf_isnumber(59));   /* ;   */
    TEST_ASSERT_FALSE(utf_isnumber(60));   /* <   */
    TEST_ASSERT_FALSE(utf_isnumber(61));   /* =   */
    TEST_ASSERT_FALSE(utf_isnumber(62));   /* >   */
    TEST_ASSERT_FALSE(utf_isnumber(63));   /* ?   */
    TEST_ASSERT_FALSE(utf_isnumber(64));   /* @   */
    TEST_ASSERT_FALSE(utf_isnumber(65));   /* A   */
    TEST_ASSERT_FALSE(utf_isnumber(66));   /* B   */
    TEST_ASSERT_FALSE(utf_isnumber(67));   /* C   */
    TEST_ASSERT_FALSE(utf_isnumber(68));   /* D   */
    TEST_ASSERT_FALSE(utf_isnumber(69));   /* E   */
    TEST_ASSERT_FALSE(utf_isnumber(70));   /* F   */
    TEST_ASSERT_FALSE(utf_isnumber(71));   /* G   */
    TEST_ASSERT_FALSE(utf_isnumber(72));   /* H   */
    TEST_ASSERT_FALSE(utf_isnumber(73));   /* I   */
    TEST_ASSERT_FALSE(utf_isnumber(74));   /* J   */
    TEST_ASSERT_FALSE(utf_isnumber(75));   /* K   */
    TEST_ASSERT_FALSE(utf_isnumber(76));   /* L   */
    TEST_ASSERT_FALSE(utf_isnumber(77));   /* M   */
    TEST_ASSERT_FALSE(utf_isnumber(78));   /* N   */
    TEST_ASSERT_FALSE(utf_isnumber(79));   /* O   */
    TEST_ASSERT_FALSE(utf_isnumber(80));   /* P   */
    TEST_ASSERT_FALSE(utf_isnumber(81));   /* Q   */
    TEST_ASSERT_FALSE(utf_isnumber(82));   /* R   */
    TEST_ASSERT_FALSE(utf_isnumber(83));   /* S   */
    TEST_ASSERT_FALSE(utf_isnumber(84));   /* T   */
    TEST_ASSERT_FALSE(utf_isnumber(85));   /* U   */
    TEST_ASSERT_FALSE(utf_isnumber(86));   /* V   */
    TEST_ASSERT_FALSE(utf_isnumber(87));   /* W   */
    TEST_ASSERT_FALSE(utf_isnumber(88));   /* X   */
    TEST_ASSERT_FALSE(utf_isnumber(89));   /* Y   */
    TEST_ASSERT_FALSE(utf_isnumber(90));   /* Z   */
    TEST_ASSERT_FALSE(utf_isnumber(91));   /* [   */
    TEST_ASSERT_FALSE(utf_isnumber(92));   /* \   */
    TEST_ASSERT_FALSE(utf_isnumber(93));   /* ]   */
    TEST_ASSERT_FALSE(utf_isnumber(94));   /* ^   */
    TEST_ASSERT_FALSE(utf_isnumber(95));   /* _   */
    TEST_ASSERT_FALSE(utf_isnumber(96));   /* `   */
    TEST_ASSERT_FALSE(utf_isnumber(97));   /* a   */
    TEST_ASSERT_FALSE(utf_isnumber(98));   /* b   */
    TEST_ASSERT_FALSE(utf_isnumber(99));   /* c   */
    TEST_ASSERT_FALSE(utf_isnumber(100));  /* d   */
    TEST_ASSERT_FALSE(utf_isnumber(101));  /* e   */
    TEST_ASSERT_FALSE(utf_isnumber(102));  /* f   */
    TEST_ASSERT_FALSE(utf_isnumber(103));  /* g   */
    TEST_ASSERT_FALSE(utf_isnumber(104));  /* h   */
    TEST_ASSERT_FALSE(utf_isnumber(105));  /* i   */
    TEST_ASSERT_FALSE(utf_isnumber(106));  /* j   */
    TEST_ASSERT_FALSE(utf_isnumber(107));  /* k   */
    TEST_ASSERT_FALSE(utf_isnumber(108));  /* l   */
    TEST_ASSERT_FALSE(utf_isnumber(109));  /* m   */
    TEST_ASSERT_FALSE(utf_isnumber(110));  /* n   */
    TEST_ASSERT_FALSE(utf_isnumber(111));  /* o   */
    TEST_ASSERT_FALSE(utf_isnumber(112));  /* p   */
    TEST_ASSERT_FALSE(utf_isnumber(113));  /* q   */
    TEST_ASSERT_FALSE(utf_isnumber(114));  /* r   */
    TEST_ASSERT_FALSE(utf_isnumber(115));  /* s   */
    TEST_ASSERT_FALSE(utf_isnumber(116));  /* t   */
    TEST_ASSERT_FALSE(utf_isnumber(117));  /* u   */
    TEST_ASSERT_FALSE(utf_isnumber(118));  /* v   */
    TEST_ASSERT_FALSE(utf_isnumber(119));  /* w   */
    TEST_ASSERT_FALSE(utf_isnumber(120));  /* x   */
    TEST_ASSERT_FALSE(utf_isnumber(121));  /* y   */
    TEST_ASSERT_FALSE(utf_isnumber(122));  /* z   */
    TEST_ASSERT_FALSE(utf_isnumber(123));  /* {   */
    TEST_ASSERT_FALSE(utf_isnumber(124));  /* |   */
    TEST_ASSERT_FALSE(utf_isnumber(125));  /* }   */
    TEST_ASSERT_FALSE(utf_isnumber(126));  /* ~   */
    TEST_ASSERT_FALSE(utf_isnumber(127));  /* DEL */
    TEST_ASSERT_TRUE(utf_isnumber(178));   /* ²   */
    TEST_ASSERT_TRUE(utf_isnumber(8528));  /* ⅐   */
}

void test_isinteger(void)
{
    TEST_ASSERT_FALSE(utf_isinteger(0));     /* NUL */
    TEST_ASSERT_FALSE(utf_isinteger(1));     /* SOH */
    TEST_ASSERT_FALSE(utf_isinteger(2));     /* STX */
    TEST_ASSERT_FALSE(utf_isinteger(3));     /* ETX */
    TEST_ASSERT_FALSE(utf_isinteger(4));     /* EOT */
    TEST_ASSERT_FALSE(utf_isinteger(5));     /* ENQ */
    TEST_ASSERT_FALSE(utf_isinteger(6));     /* ACK */
    TEST_ASSERT_FALSE(utf_isinteger(7));     /* BEL */
    TEST_ASSERT_FALSE(utf_isinteger(8));     /* BS  */
    TEST_ASSERT_FALSE(utf_isinteger(9));     /* HT  */
    TEST_ASSERT_FALSE(utf_isinteger(10));    /* CR  */
    TEST_ASSERT_FALSE(utf_isinteger(11));    /* VT  */
    TEST_ASSERT_FALSE(utf_isinteger(12));    /* FF  */
    TEST_ASSERT_FALSE(utf_isinteger(13));    /* LF  */
    TEST_ASSERT_FALSE(utf_isinteger(14));    /* SO  */
    TEST_ASSERT_FALSE(utf_isinteger(15));    /* SI  */
    TEST_ASSERT_FALSE(utf_isinteger(16));    /* DLE */
    TEST_ASSERT_FALSE(utf_isinteger(17));    /* DC1 */
    TEST_ASSERT_FALSE(utf_isinteger(18));    /* DC2 */
    TEST_ASSERT_FALSE(utf_isinteger(19));    /* DC3 */
    TEST_ASSERT_FALSE(utf_isinteger(20));    /* DC4 */
    TEST_ASSERT_FALSE(utf_isinteger(21));    /* NAK */
    TEST_ASSERT_FALSE(utf_isinteger(22));    /* SYN */
    TEST_ASSERT_FALSE(utf_isinteger(23));    /* ETB */
    TEST_ASSERT_FALSE(utf_isinteger(24));    /* CAN */
    TEST_ASSERT_FALSE(utf_isinteger(25));    /* EM  */
    TEST_ASSERT_FALSE(utf_isinteger(26));    /* SUB */
    TEST_ASSERT_FALSE(utf_isinteger(27));    /* ESC */
    TEST_ASSERT_FALSE(utf_isinteger(28));    /* FS  */
    TEST_ASSERT_FALSE(utf_isinteger(29));    /* GS  */
    TEST_ASSERT_FALSE(utf_isinteger(30));    /* RS  */
    TEST_ASSERT_FALSE(utf_isinteger(31));    /* US  */
    TEST_ASSERT_FALSE(utf_isinteger(32));    /* SP  */
    TEST_ASSERT_FALSE(utf_isinteger(33));    /* !   */
    TEST_ASSERT_FALSE(utf_isinteger(34));    /* "   */
    TEST_ASSERT_FALSE(utf_isinteger(35));    /* #   */
    TEST_ASSERT_FALSE(utf_isinteger(36));    /* $   */
    TEST_ASSERT_FALSE(utf_isinteger(37));    /* %   */
    TEST_ASSERT_FALSE(utf_isinteger(38));    /* &   */
    TEST_ASSERT_FALSE(utf_isinteger(39));    /* '   */
    TEST_ASSERT_FALSE(utf_isinteger(40));    /* (   */
    TEST_ASSERT_FALSE(utf_isinteger(41));    /* )   */
    TEST_ASSERT_FALSE(utf_isinteger(42));    /* *   */
    TEST_ASSERT_FALSE(utf_isinteger(43));    /* +   */
    TEST_ASSERT_FALSE(utf_isinteger(44));    /* ,   */
    TEST_ASSERT_FALSE(utf_isinteger(45));    /* -   */
    TEST_ASSERT_FALSE(utf_isinteger(46));    /* .   */
    TEST_ASSERT_FALSE(utf_isinteger(47));    /* /   */
    TEST_ASSERT_TRUE(utf_isinteger(48));     /* 0   */
    TEST_ASSERT_TRUE(utf_isinteger(49));     /* 1   */
    TEST_ASSERT_TRUE(utf_isinteger(50));     /* 2   */
    TEST_ASSERT_TRUE(utf_isinteger(51));     /* 3   */
    TEST_ASSERT_TRUE(utf_isinteger(52));     /* 4   */
    TEST_ASSERT_TRUE(utf_isinteger(53));     /* 5   */
    TEST_ASSERT_TRUE(utf_isinteger(54));     /* 6   */
    TEST_ASSERT_TRUE(utf_isinteger(55));     /* 7   */
    TEST_ASSERT_TRUE(utf_isinteger(56));     /* 8   */
    TEST_ASSERT_TRUE(utf_isinteger(57));     /* 9   */
    TEST_ASSERT_FALSE(utf_isinteger(58));    /* :   */
    TEST_ASSERT_FALSE(utf_isinteger(59));    /* ;   */
    TEST_ASSERT_FALSE(utf_isinteger(60));    /* <   */
    TEST_ASSERT_FALSE(utf_isinteger(61));    /* =   */
    TEST_ASSERT_FALSE(utf_isinteger(62));    /* >   */
    TEST_ASSERT_FALSE(utf_isinteger(63));    /* ?   */
    TEST_ASSERT_FALSE(utf_isinteger(64));    /* @   */
    TEST_ASSERT_FALSE(utf_isinteger(65));    /* A   */
    TEST_ASSERT_FALSE(utf_isinteger(66));    /* B   */
    TEST_ASSERT_FALSE(utf_isinteger(67));    /* C   */
    TEST_ASSERT_FALSE(utf_isinteger(68));    /* D   */
    TEST_ASSERT_FALSE(utf_isinteger(69));    /* E   */
    TEST_ASSERT_FALSE(utf_isinteger(70));    /* F   */
    TEST_ASSERT_FALSE(utf_isinteger(71));    /* G   */
    TEST_ASSERT_FALSE(utf_isinteger(72));    /* H   */
    TEST_ASSERT_FALSE(utf_isinteger(73));    /* I   */
    TEST_ASSERT_FALSE(utf_isinteger(74));    /* J   */
    TEST_ASSERT_FALSE(utf_isinteger(75));    /* K   */
    TEST_ASSERT_FALSE(utf_isinteger(76));    /* L   */
    TEST_ASSERT_FALSE(utf_isinteger(77));    /* M   */
    TEST_ASSERT_FALSE(utf_isinteger(78));    /* N   */
    TEST_ASSERT_FALSE(utf_isinteger(79));    /* O   */
    TEST_ASSERT_FALSE(utf_isinteger(80));    /* P   */
    TEST_ASSERT_FALSE(utf_isinteger(81));    /* Q   */
    TEST_ASSERT_FALSE(utf_isinteger(82));    /* R   */
    TEST_ASSERT_FALSE(utf_isinteger(83));    /* S   */
    TEST_ASSERT_FALSE(utf_isinteger(84));    /* T   */
    TEST_ASSERT_FALSE(utf_isinteger(85));    /* U   */
    TEST_ASSERT_FALSE(utf_isinteger(86));    /* V   */
    TEST_ASSERT_FALSE(utf_isinteger(87));    /* W   */
    TEST_ASSERT_FALSE(utf_isinteger(88));    /* X   */
    TEST_ASSERT_FALSE(utf_isinteger(89));    /* Y   */
    TEST_ASSERT_FALSE(utf_isinteger(90));    /* Z   */
    TEST_ASSERT_FALSE(utf_isinteger(91));    /* [   */
    TEST_ASSERT_FALSE(utf_isinteger(92));    /* \   */
    TEST_ASSERT_FALSE(utf_isinteger(93));    /* ]   */
    TEST_ASSERT_FALSE(utf_isinteger(94));    /* ^   */
    TEST_ASSERT_FALSE(utf_isinteger(95));    /* _   */
    TEST_ASSERT_FALSE(utf_isinteger(96));    /* `   */
    TEST_ASSERT_FALSE(utf_isinteger(97));    /* a   */
    TEST_ASSERT_FALSE(utf_isinteger(98));    /* b   */
    TEST_ASSERT_FALSE(utf_isinteger(99));    /* c   */
    TEST_ASSERT_FALSE(utf_isinteger(100));   /* d   */
    TEST_ASSERT_FALSE(utf_isinteger(101));   /* e   */
    TEST_ASSERT_FALSE(utf_isinteger(102));   /* f   */
    TEST_ASSERT_FALSE(utf_isinteger(103));   /* g   */
    TEST_ASSERT_FALSE(utf_isinteger(104));   /* h   */
    TEST_ASSERT_FALSE(utf_isinteger(105));   /* i   */
    TEST_ASSERT_FALSE(utf_isinteger(106));   /* j   */
    TEST_ASSERT_FALSE(utf_isinteger(107));   /* k   */
    TEST_ASSERT_FALSE(utf_isinteger(108));   /* l   */
    TEST_ASSERT_FALSE(utf_isinteger(109));   /* m   */
    TEST_ASSERT_FALSE(utf_isinteger(110));   /* n   */
    TEST_ASSERT_FALSE(utf_isinteger(111));   /* o   */
    TEST_ASSERT_FALSE(utf_isinteger(112));   /* p   */
    TEST_ASSERT_FALSE(utf_isinteger(113));   /* q   */
    TEST_ASSERT_FALSE(utf_isinteger(114));   /* r   */
    TEST_ASSERT_FALSE(utf_isinteger(115));   /* s   */
    TEST_ASSERT_FALSE(utf_isinteger(116));   /* t   */
    TEST_ASSERT_FALSE(utf_isinteger(117));   /* u   */
    TEST_ASSERT_FALSE(utf_isinteger(118));   /* v   */
    TEST_ASSERT_FALSE(utf_isinteger(119));   /* w   */
    TEST_ASSERT_FALSE(utf_isinteger(120));   /* x   */
    TEST_ASSERT_FALSE(utf_isinteger(121));   /* y   */
    TEST_ASSERT_FALSE(utf_isinteger(122));   /* z   */
    TEST_ASSERT_FALSE(utf_isinteger(123));   /* {   */
    TEST_ASSERT_FALSE(utf_isinteger(124));   /* |   */
    TEST_ASSERT_FALSE(utf_isinteger(125));   /* }   */
    TEST_ASSERT_FALSE(utf_isinteger(126));   /* ~   */
    TEST_ASSERT_FALSE(utf_isinteger(127));   /* DEL */
    TEST_ASSERT_FALSE(utf_isinteger(178));   /* ²   */
    TEST_ASSERT_FALSE(utf_isinteger(8528));  /* ⅐   */
}

void test_isgraph(void)
{
    TEST_ASSERT_FALSE(utf_isgraph(0));    /* NUL */
    TEST_ASSERT_FALSE(utf_isgraph(1));    /* SOH */
    TEST_ASSERT_FALSE(utf_isgraph(2));    /* STX */
    TEST_ASSERT_FALSE(utf_isgraph(3));    /* ETX */
    TEST_ASSERT_FALSE(utf_isgraph(4));    /* EOT */
    TEST_ASSERT_FALSE(utf_isgraph(5));    /* ENQ */
    TEST_ASSERT_FALSE(utf_isgraph(6));    /* ACK */
    TEST_ASSERT_FALSE(utf_isgraph(7));    /* BEL */
    TEST_ASSERT_FALSE(utf_isgraph(8));    /* BS  */
    TEST_ASSERT_FALSE(utf_isgraph(9));    /* HT  */
    TEST_ASSERT_FALSE(utf_isgraph(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_isgraph(11));   /* VT  */
    TEST_ASSERT_FALSE(utf_isgraph(12));   /* FF  */
    TEST_ASSERT_FALSE(utf_isgraph(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_isgraph(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_isgraph(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_isgraph(14));   /* SO  */
    TEST_ASSERT_FALSE(utf_isgraph(15));   /* SI  */
    TEST_ASSERT_FALSE(utf_isgraph(16));   /* DLE */
    TEST_ASSERT_FALSE(utf_isgraph(17));   /* DC1 */
    TEST_ASSERT_FALSE(utf_isgraph(18));   /* DC2 */
    TEST_ASSERT_FALSE(utf_isgraph(19));   /* DC3 */
    TEST_ASSERT_FALSE(utf_isgraph(20));   /* DC4 */
    TEST_ASSERT_FALSE(utf_isgraph(21));   /* NAK */
    TEST_ASSERT_FALSE(utf_isgraph(22));   /* SYN */
    TEST_ASSERT_FALSE(utf_isgraph(23));   /* ETB */
    TEST_ASSERT_FALSE(utf_isgraph(24));   /* CAN */
    TEST_ASSERT_FALSE(utf_isgraph(25));   /* EM  */
    TEST_ASSERT_FALSE(utf_isgraph(26));   /* SUB */
    TEST_ASSERT_FALSE(utf_isgraph(27));   /* ESC */
    TEST_ASSERT_FALSE(utf_isgraph(28));   /* FS  */
    TEST_ASSERT_FALSE(utf_isgraph(29));   /* GS  */
    TEST_ASSERT_FALSE(utf_isgraph(30));   /* RS  */
    TEST_ASSERT_FALSE(utf_isgraph(31));   /* US  */
    TEST_ASSERT_FALSE(utf_isgraph(32));   /* SP  */
    TEST_ASSERT_TRUE(utf_isgraph(33));    /* !   */
    TEST_ASSERT_TRUE(utf_isgraph(34));    /* "   */
    TEST_ASSERT_TRUE(utf_isgraph(35));    /* #   */
    TEST_ASSERT_TRUE(utf_isgraph(36));    /* $   */
    TEST_ASSERT_TRUE(utf_isgraph(37));    /* %   */
    TEST_ASSERT_TRUE(utf_isgraph(38));    /* &   */
    TEST_ASSERT_TRUE(utf_isgraph(39));    /* '   */
    TEST_ASSERT_TRUE(utf_isgraph(40));    /* (   */
    TEST_ASSERT_TRUE(utf_isgraph(41));    /* )   */
    TEST_ASSERT_TRUE(utf_isgraph(42));    /* *   */
    TEST_ASSERT_TRUE(utf_isgraph(43));    /* +   */
    TEST_ASSERT_TRUE(utf_isgraph(44));    /* ,   */
    TEST_ASSERT_TRUE(utf_isgraph(45));    /* -   */
    TEST_ASSERT_TRUE(utf_isgraph(46));    /* .   */
    TEST_ASSERT_TRUE(utf_isgraph(47));    /* /   */
    TEST_ASSERT_TRUE(utf_isgraph(48));    /* 0   */
    TEST_ASSERT_TRUE(utf_isgraph(49));    /* 1   */
    TEST_ASSERT_TRUE(utf_isgraph(50));    /* 2   */
    TEST_ASSERT_TRUE(utf_isgraph(51));    /* 3   */
    TEST_ASSERT_TRUE(utf_isgraph(52));    /* 4   */
    TEST_ASSERT_TRUE(utf_isgraph(53));    /* 5   */
    TEST_ASSERT_TRUE(utf_isgraph(54));    /* 6   */
    TEST_ASSERT_TRUE(utf_isgraph(55));    /* 7   */
    TEST_ASSERT_TRUE(utf_isgraph(56));    /* 8   */
    TEST_ASSERT_TRUE(utf_isgraph(57));    /* 9   */
    TEST_ASSERT_TRUE(utf_isgraph(58));    /* :   */
    TEST_ASSERT_TRUE(utf_isgraph(59));    /* ;   */
    TEST_ASSERT_TRUE(utf_isgraph(60));    /* <   */
    TEST_ASSERT_TRUE(utf_isgraph(61));    /* =   */
    TEST_ASSERT_TRUE(utf_isgraph(62));    /* >   */
    TEST_ASSERT_TRUE(utf_isgraph(63));    /* ?   */
    TEST_ASSERT_TRUE(utf_isgraph(64));    /* @   */
    TEST_ASSERT_TRUE(utf_isgraph(65));    /* A   */
    TEST_ASSERT_TRUE(utf_isgraph(66));    /* B   */
    TEST_ASSERT_TRUE(utf_isgraph(67));    /* C   */
    TEST_ASSERT_TRUE(utf_isgraph(68));    /* D   */
    TEST_ASSERT_TRUE(utf_isgraph(69));    /* E   */
    TEST_ASSERT_TRUE(utf_isgraph(70));    /* F   */
    TEST_ASSERT_TRUE(utf_isgraph(71));    /* G   */
    TEST_ASSERT_TRUE(utf_isgraph(72));    /* H   */
    TEST_ASSERT_TRUE(utf_isgraph(73));    /* I   */
    TEST_ASSERT_TRUE(utf_isgraph(74));    /* J   */
    TEST_ASSERT_TRUE(utf_isgraph(75));    /* K   */
    TEST_ASSERT_TRUE(utf_isgraph(76));    /* L   */
    TEST_ASSERT_TRUE(utf_isgraph(77));    /* M   */
    TEST_ASSERT_TRUE(utf_isgraph(78));    /* N   */
    TEST_ASSERT_TRUE(utf_isgraph(79));    /* O   */
    TEST_ASSERT_TRUE(utf_isgraph(80));    /* P   */
    TEST_ASSERT_TRUE(utf_isgraph(81));    /* Q   */
    TEST_ASSERT_TRUE(utf_isgraph(82));    /* R   */
    TEST_ASSERT_TRUE(utf_isgraph(83));    /* S   */
    TEST_ASSERT_TRUE(utf_isgraph(84));    /* T   */
    TEST_ASSERT_TRUE(utf_isgraph(85));    /* U   */
    TEST_ASSERT_TRUE(utf_isgraph(86));    /* V   */
    TEST_ASSERT_TRUE(utf_isgraph(87));    /* W   */
    TEST_ASSERT_TRUE(utf_isgraph(88));    /* X   */
    TEST_ASSERT_TRUE(utf_isgraph(89));    /* Y   */
    TEST_ASSERT_TRUE(utf_isgraph(90));    /* Z   */
    TEST_ASSERT_TRUE(utf_isgraph(91));    /* [   */
    TEST_ASSERT_TRUE(utf_isgraph(92));    /* \   */
    TEST_ASSERT_TRUE(utf_isgraph(93));    /* ]   */
    TEST_ASSERT_TRUE(utf_isgraph(94));    /* ^   */
    TEST_ASSERT_TRUE(utf_isgraph(95));    /* _   */
    TEST_ASSERT_TRUE(utf_isgraph(96));    /* `   */
    TEST_ASSERT_TRUE(utf_isgraph(97));    /* a   */
    TEST_ASSERT_TRUE(utf_isgraph(98));    /* b   */
    TEST_ASSERT_TRUE(utf_isgraph(99));    /* c   */
    TEST_ASSERT_TRUE(utf_isgraph(100));   /* d   */
    TEST_ASSERT_TRUE(utf_isgraph(101));   /* e   */
    TEST_ASSERT_TRUE(utf_isgraph(102));   /* f   */
    TEST_ASSERT_TRUE(utf_isgraph(103));   /* g   */
    TEST_ASSERT_TRUE(utf_isgraph(104));   /* h   */
    TEST_ASSERT_TRUE(utf_isgraph(105));   /* i   */
    TEST_ASSERT_TRUE(utf_isgraph(106));   /* j   */
    TEST_ASSERT_TRUE(utf_isgraph(107));   /* k   */
    TEST_ASSERT_TRUE(utf_isgraph(108));   /* l   */
    TEST_ASSERT_TRUE(utf_isgraph(109));   /* m   */
    TEST_ASSERT_TRUE(utf_isgraph(110));   /* n   */
    TEST_ASSERT_TRUE(utf_isgraph(111));   /* o   */
    TEST_ASSERT_TRUE(utf_isgraph(112));   /* p   */
    TEST_ASSERT_TRUE(utf_isgraph(113));   /* q   */
    TEST_ASSERT_TRUE(utf_isgraph(114));   /* r   */
    TEST_ASSERT_TRUE(utf_isgraph(115));   /* s   */
    TEST_ASSERT_TRUE(utf_isgraph(116));   /* t   */
    TEST_ASSERT_TRUE(utf_isgraph(117));   /* u   */
    TEST_ASSERT_TRUE(utf_isgraph(118));   /* v   */
    TEST_ASSERT_TRUE(utf_isgraph(119));   /* w   */
    TEST_ASSERT_TRUE(utf_isgraph(120));   /* x   */
    TEST_ASSERT_TRUE(utf_isgraph(121));   /* y   */
    TEST_ASSERT_TRUE(utf_isgraph(122));   /* z   */
    TEST_ASSERT_TRUE(utf_isgraph(123));   /* {   */
    TEST_ASSERT_TRUE(utf_isgraph(124));   /* |   */
    TEST_ASSERT_TRUE(utf_isgraph(125));   /* }   */
    TEST_ASSERT_TRUE(utf_isgraph(126));   /* ~   */
    TEST_ASSERT_FALSE(utf_isgraph(127));  /* DEL */
    TEST_ASSERT_TRUE(utf_isgraph(168));   /* ¨   */
    TEST_ASSERT_TRUE(utf_isgraph(178));   /* ²   */
    TEST_ASSERT_FALSE(utf_isgraph(2363)); /*     */
}

void test_islower(void)
{
    TEST_ASSERT_FALSE(utf_islower(0));    /* NUL */
    TEST_ASSERT_FALSE(utf_islower(1));    /* SOH */
    TEST_ASSERT_FALSE(utf_islower(2));    /* STX */
    TEST_ASSERT_FALSE(utf_islower(3));    /* ETX */
    TEST_ASSERT_FALSE(utf_islower(4));    /* EOT */
    TEST_ASSERT_FALSE(utf_islower(5));    /* ENQ */
    TEST_ASSERT_FALSE(utf_islower(6));    /* ACK */
    TEST_ASSERT_FALSE(utf_islower(7));    /* BEL */
    TEST_ASSERT_FALSE(utf_islower(8));    /* BS  */
    TEST_ASSERT_FALSE(utf_islower(9));    /* HT  */
    TEST_ASSERT_FALSE(utf_islower(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_islower(11));   /* VT  */
    TEST_ASSERT_FALSE(utf_islower(12));   /* FF  */
    TEST_ASSERT_FALSE(utf_islower(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_islower(14));   /* SO  */
    TEST_ASSERT_FALSE(utf_islower(15));   /* SI  */
    TEST_ASSERT_FALSE(utf_islower(16));   /* DLE */
    TEST_ASSERT_FALSE(utf_islower(17));   /* DC1 */
    TEST_ASSERT_FALSE(utf_islower(18));   /* DC2 */
    TEST_ASSERT_FALSE(utf_islower(19));   /* DC3 */
    TEST_ASSERT_FALSE(utf_islower(20));   /* DC4 */
    TEST_ASSERT_FALSE(utf_islower(21));   /* NAK */
    TEST_ASSERT_FALSE(utf_islower(22));   /* SYN */
    TEST_ASSERT_FALSE(utf_islower(23));   /* ETB */
    TEST_ASSERT_FALSE(utf_islower(24));   /* CAN */
    TEST_ASSERT_FALSE(utf_islower(25));   /* EM  */
    TEST_ASSERT_FALSE(utf_islower(26));   /* SUB */
    TEST_ASSERT_FALSE(utf_islower(27));   /* ESC */
    TEST_ASSERT_FALSE(utf_islower(28));   /* FS  */
    TEST_ASSERT_FALSE(utf_islower(29));   /* GS  */
    TEST_ASSERT_FALSE(utf_islower(30));   /* RS  */
    TEST_ASSERT_FALSE(utf_islower(31));   /* US  */
    TEST_ASSERT_FALSE(utf_islower(32));   /* SP  */
    TEST_ASSERT_FALSE(utf_islower(33));   /* !   */
    TEST_ASSERT_FALSE(utf_islower(34));   /* "   */
    TEST_ASSERT_FALSE(utf_islower(35));   /* #   */
    TEST_ASSERT_FALSE(utf_islower(36));   /* $   */
    TEST_ASSERT_FALSE(utf_islower(37));   /* %   */
    TEST_ASSERT_FALSE(utf_islower(38));   /* &   */
    TEST_ASSERT_FALSE(utf_islower(39));   /* '   */
    TEST_ASSERT_FALSE(utf_islower(40));   /* (   */
    TEST_ASSERT_FALSE(utf_islower(41));   /* )   */
    TEST_ASSERT_FALSE(utf_islower(42));   /* *   */
    TEST_ASSERT_FALSE(utf_islower(43));   /* +   */
    TEST_ASSERT_FALSE(utf_islower(44));   /* ,   */
    TEST_ASSERT_FALSE(utf_islower(45));   /* -   */
    TEST_ASSERT_FALSE(utf_islower(46));   /* .   */
    TEST_ASSERT_FALSE(utf_islower(47));   /* /   */
    TEST_ASSERT_FALSE(utf_islower(48));   /* 0   */
    TEST_ASSERT_FALSE(utf_islower(49));   /* 1   */
    TEST_ASSERT_FALSE(utf_islower(50));   /* 2   */
    TEST_ASSERT_FALSE(utf_islower(51));   /* 3   */
    TEST_ASSERT_FALSE(utf_islower(52));   /* 4   */
    TEST_ASSERT_FALSE(utf_islower(53));   /* 5   */
    TEST_ASSERT_FALSE(utf_islower(54));   /* 6   */
    TEST_ASSERT_FALSE(utf_islower(55));   /* 7   */
    TEST_ASSERT_FALSE(utf_islower(56));   /* 8   */
    TEST_ASSERT_FALSE(utf_islower(57));   /* 9   */
    TEST_ASSERT_FALSE(utf_islower(58));   /* :   */
    TEST_ASSERT_FALSE(utf_islower(59));   /* ;   */
    TEST_ASSERT_FALSE(utf_islower(60));   /* <   */
    TEST_ASSERT_FALSE(utf_islower(61));   /* =   */
    TEST_ASSERT_FALSE(utf_islower(62));   /* >   */
    TEST_ASSERT_FALSE(utf_islower(63));   /* ?   */
    TEST_ASSERT_FALSE(utf_islower(64));   /* @   */
    TEST_ASSERT_FALSE(utf_islower(65));   /* A   */
    TEST_ASSERT_FALSE(utf_islower(66));   /* B   */
    TEST_ASSERT_FALSE(utf_islower(67));   /* C   */
    TEST_ASSERT_FALSE(utf_islower(68));   /* D   */
    TEST_ASSERT_FALSE(utf_islower(69));   /* E   */
    TEST_ASSERT_FALSE(utf_islower(70));   /* F   */
    TEST_ASSERT_FALSE(utf_islower(71));   /* G   */
    TEST_ASSERT_FALSE(utf_islower(72));   /* H   */
    TEST_ASSERT_FALSE(utf_islower(73));   /* I   */
    TEST_ASSERT_FALSE(utf_islower(74));   /* J   */
    TEST_ASSERT_FALSE(utf_islower(75));   /* K   */
    TEST_ASSERT_FALSE(utf_islower(76));   /* L   */
    TEST_ASSERT_FALSE(utf_islower(77));   /* M   */
    TEST_ASSERT_FALSE(utf_islower(78));   /* N   */
    TEST_ASSERT_FALSE(utf_islower(79));   /* O   */
    TEST_ASSERT_FALSE(utf_islower(80));   /* P   */
    TEST_ASSERT_FALSE(utf_islower(81));   /* Q   */
    TEST_ASSERT_FALSE(utf_islower(82));   /* R   */
    TEST_ASSERT_FALSE(utf_islower(83));   /* S   */
    TEST_ASSERT_FALSE(utf_islower(84));   /* T   */
    TEST_ASSERT_FALSE(utf_islower(85));   /* U   */
    TEST_ASSERT_FALSE(utf_islower(86));   /* V   */
    TEST_ASSERT_FALSE(utf_islower(87));   /* W   */
    TEST_ASSERT_FALSE(utf_islower(88));   /* X   */
    TEST_ASSERT_FALSE(utf_islower(89));   /* Y   */
    TEST_ASSERT_FALSE(utf_islower(90));   /* Z   */
    TEST_ASSERT_FALSE(utf_islower(91));   /* [   */
    TEST_ASSERT_FALSE(utf_islower(92));   /* \   */
    TEST_ASSERT_FALSE(utf_islower(93));   /* ]   */
    TEST_ASSERT_FALSE(utf_islower(94));   /* ^   */
    TEST_ASSERT_FALSE(utf_islower(95));   /* _   */
    TEST_ASSERT_FALSE(utf_islower(96));   /* `   */
    TEST_ASSERT_TRUE(utf_islower(97));    /* a   */
    TEST_ASSERT_TRUE(utf_islower(98));    /* b   */
    TEST_ASSERT_TRUE(utf_islower(99));    /* c   */
    TEST_ASSERT_TRUE(utf_islower(100));   /* d   */
    TEST_ASSERT_TRUE(utf_islower(101));   /* e   */
    TEST_ASSERT_TRUE(utf_islower(102));   /* f   */
    TEST_ASSERT_TRUE(utf_islower(103));   /* g   */
    TEST_ASSERT_TRUE(utf_islower(104));   /* h   */
    TEST_ASSERT_TRUE(utf_islower(105));   /* i   */
    TEST_ASSERT_TRUE(utf_islower(106));   /* j   */
    TEST_ASSERT_TRUE(utf_islower(107));   /* k   */
    TEST_ASSERT_TRUE(utf_islower(108));   /* l   */
    TEST_ASSERT_TRUE(utf_islower(109));   /* m   */
    TEST_ASSERT_TRUE(utf_islower(110));   /* n   */
    TEST_ASSERT_TRUE(utf_islower(111));   /* o   */
    TEST_ASSERT_TRUE(utf_islower(112));   /* p   */
    TEST_ASSERT_TRUE(utf_islower(113));   /* q   */
    TEST_ASSERT_TRUE(utf_islower(114));   /* r   */
    TEST_ASSERT_TRUE(utf_islower(115));   /* s   */
    TEST_ASSERT_TRUE(utf_islower(116));   /* t   */
    TEST_ASSERT_TRUE(utf_islower(117));   /* u   */
    TEST_ASSERT_TRUE(utf_islower(118));   /* v   */
    TEST_ASSERT_TRUE(utf_islower(119));   /* w   */
    TEST_ASSERT_TRUE(utf_islower(120));   /* x   */
    TEST_ASSERT_TRUE(utf_islower(121));   /* y   */
    TEST_ASSERT_TRUE(utf_islower(122));   /* z   */
    TEST_ASSERT_FALSE(utf_islower(123));  /* {   */
    TEST_ASSERT_FALSE(utf_islower(124));  /* |   */
    TEST_ASSERT_FALSE(utf_islower(125));  /* }   */
    TEST_ASSERT_FALSE(utf_islower(126));  /* ~   */
    TEST_ASSERT_FALSE(utf_islower(127));  /* DEL */
    TEST_ASSERT_FALSE(utf_islower(178));  /* ²   */
}

void test_isprint(void)
{
    TEST_ASSERT_FALSE(utf_isprint(0));    /* NUL */
    TEST_ASSERT_FALSE(utf_isprint(1));    /* SOH */
    TEST_ASSERT_FALSE(utf_isprint(2));    /* STX */
    TEST_ASSERT_FALSE(utf_isprint(3));    /* ETX */
    TEST_ASSERT_FALSE(utf_isprint(4));    /* EOT */
    TEST_ASSERT_FALSE(utf_isprint(5));    /* ENQ */
    TEST_ASSERT_FALSE(utf_isprint(6));    /* ACK */
    TEST_ASSERT_FALSE(utf_isprint(7));    /* BEL */
    TEST_ASSERT_FALSE(utf_isprint(8));    /* BS  */
    TEST_ASSERT_FALSE(utf_isprint(9));    /* HT  */
    TEST_ASSERT_FALSE(utf_isprint(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_isprint(11));   /* VT  */
    TEST_ASSERT_FALSE(utf_isprint(12));   /* FF  */
    TEST_ASSERT_FALSE(utf_isprint(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_isprint(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_isprint(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_isprint(14));   /* SO  */
    TEST_ASSERT_FALSE(utf_isprint(15));   /* SI  */
    TEST_ASSERT_FALSE(utf_isprint(16));   /* DLE */
    TEST_ASSERT_FALSE(utf_isprint(17));   /* DC1 */
    TEST_ASSERT_FALSE(utf_isprint(18));   /* DC2 */
    TEST_ASSERT_FALSE(utf_isprint(19));   /* DC3 */
    TEST_ASSERT_FALSE(utf_isprint(20));   /* DC4 */
    TEST_ASSERT_FALSE(utf_isprint(21));   /* NAK */
    TEST_ASSERT_FALSE(utf_isprint(22));   /* SYN */
    TEST_ASSERT_FALSE(utf_isprint(23));   /* ETB */
    TEST_ASSERT_FALSE(utf_isprint(24));   /* CAN */
    TEST_ASSERT_FALSE(utf_isprint(25));   /* EM  */
    TEST_ASSERT_FALSE(utf_isprint(26));   /* SUB */
    TEST_ASSERT_FALSE(utf_isprint(27));   /* ESC */
    TEST_ASSERT_FALSE(utf_isprint(28));   /* FS  */
    TEST_ASSERT_FALSE(utf_isprint(29));   /* GS  */
    TEST_ASSERT_FALSE(utf_isprint(30));   /* RS  */
    TEST_ASSERT_FALSE(utf_isprint(31));   /* US  */
    TEST_ASSERT_TRUE(utf_isprint(32));    /* SP  */
    TEST_ASSERT_TRUE(utf_isprint(33));    /* !   */
    TEST_ASSERT_TRUE(utf_isprint(34));    /* "   */
    TEST_ASSERT_TRUE(utf_isprint(35));    /* #   */
    TEST_ASSERT_TRUE(utf_isprint(36));    /* $   */
    TEST_ASSERT_TRUE(utf_isprint(37));    /* %   */
    TEST_ASSERT_TRUE(utf_isprint(38));    /* &   */
    TEST_ASSERT_TRUE(utf_isprint(39));    /* '   */
    TEST_ASSERT_TRUE(utf_isprint(40));    /* (   */
    TEST_ASSERT_TRUE(utf_isprint(41));    /* )   */
    TEST_ASSERT_TRUE(utf_isprint(42));    /* *   */
    TEST_ASSERT_TRUE(utf_isprint(43));    /* +   */
    TEST_ASSERT_TRUE(utf_isprint(44));    /* ,   */
    TEST_ASSERT_TRUE(utf_isprint(45));    /* -   */
    TEST_ASSERT_TRUE(utf_isprint(46));    /* .   */
    TEST_ASSERT_TRUE(utf_isprint(47));    /* /   */
    TEST_ASSERT_TRUE(utf_isprint(48));    /* 0   */
    TEST_ASSERT_TRUE(utf_isprint(49));    /* 1   */
    TEST_ASSERT_TRUE(utf_isprint(50));    /* 2   */
    TEST_ASSERT_TRUE(utf_isprint(51));    /* 3   */
    TEST_ASSERT_TRUE(utf_isprint(52));    /* 4   */
    TEST_ASSERT_TRUE(utf_isprint(53));    /* 5   */
    TEST_ASSERT_TRUE(utf_isprint(54));    /* 6   */
    TEST_ASSERT_TRUE(utf_isprint(55));    /* 7   */
    TEST_ASSERT_TRUE(utf_isprint(56));    /* 8   */
    TEST_ASSERT_TRUE(utf_isprint(57));    /* 9   */
    TEST_ASSERT_TRUE(utf_isprint(58));    /* :   */
    TEST_ASSERT_TRUE(utf_isprint(59));    /* ;   */
    TEST_ASSERT_TRUE(utf_isprint(60));    /* <   */
    TEST_ASSERT_TRUE(utf_isprint(61));    /* =   */
    TEST_ASSERT_TRUE(utf_isprint(62));    /* >   */
    TEST_ASSERT_TRUE(utf_isprint(63));    /* ?   */
    TEST_ASSERT_TRUE(utf_isprint(64));    /* @   */
    TEST_ASSERT_TRUE(utf_isprint(65));    /* A   */
    TEST_ASSERT_TRUE(utf_isprint(66));    /* B   */
    TEST_ASSERT_TRUE(utf_isprint(67));    /* C   */
    TEST_ASSERT_TRUE(utf_isprint(68));    /* D   */
    TEST_ASSERT_TRUE(utf_isprint(69));    /* E   */
    TEST_ASSERT_TRUE(utf_isprint(70));    /* F   */
    TEST_ASSERT_TRUE(utf_isprint(71));    /* G   */
    TEST_ASSERT_TRUE(utf_isprint(72));    /* H   */
    TEST_ASSERT_TRUE(utf_isprint(73));    /* I   */
    TEST_ASSERT_TRUE(utf_isprint(74));    /* J   */
    TEST_ASSERT_TRUE(utf_isprint(75));    /* K   */
    TEST_ASSERT_TRUE(utf_isprint(76));    /* L   */
    TEST_ASSERT_TRUE(utf_isprint(77));    /* M   */
    TEST_ASSERT_TRUE(utf_isprint(78));    /* N   */
    TEST_ASSERT_TRUE(utf_isprint(79));    /* O   */
    TEST_ASSERT_TRUE(utf_isprint(80));    /* P   */
    TEST_ASSERT_TRUE(utf_isprint(81));    /* Q   */
    TEST_ASSERT_TRUE(utf_isprint(82));    /* R   */
    TEST_ASSERT_TRUE(utf_isprint(83));    /* S   */
    TEST_ASSERT_TRUE(utf_isprint(84));    /* T   */
    TEST_ASSERT_TRUE(utf_isprint(85));    /* U   */
    TEST_ASSERT_TRUE(utf_isprint(86));    /* V   */
    TEST_ASSERT_TRUE(utf_isprint(87));    /* W   */
    TEST_ASSERT_TRUE(utf_isprint(88));    /* X   */
    TEST_ASSERT_TRUE(utf_isprint(89));    /* Y   */
    TEST_ASSERT_TRUE(utf_isprint(90));    /* Z   */
    TEST_ASSERT_TRUE(utf_isprint(91));    /* [   */
    TEST_ASSERT_TRUE(utf_isprint(92));    /* \   */
    TEST_ASSERT_TRUE(utf_isprint(93));    /* ]   */
    TEST_ASSERT_TRUE(utf_isprint(94));    /* ^   */
    TEST_ASSERT_TRUE(utf_isprint(95));    /* _   */
    TEST_ASSERT_TRUE(utf_isprint(96));    /* `   */
    TEST_ASSERT_TRUE(utf_isprint(97));    /* a   */
    TEST_ASSERT_TRUE(utf_isprint(98));    /* b   */
    TEST_ASSERT_TRUE(utf_isprint(99));    /* c   */
    TEST_ASSERT_TRUE(utf_isprint(100));   /* d   */
    TEST_ASSERT_TRUE(utf_isprint(101));   /* e   */
    TEST_ASSERT_TRUE(utf_isprint(102));   /* f   */
    TEST_ASSERT_TRUE(utf_isprint(103));   /* g   */
    TEST_ASSERT_TRUE(utf_isprint(104));   /* h   */
    TEST_ASSERT_TRUE(utf_isprint(105));   /* i   */
    TEST_ASSERT_TRUE(utf_isprint(106));   /* j   */
    TEST_ASSERT_TRUE(utf_isprint(107));   /* k   */
    TEST_ASSERT_TRUE(utf_isprint(108));   /* l   */
    TEST_ASSERT_TRUE(utf_isprint(109));   /* m   */
    TEST_ASSERT_TRUE(utf_isprint(110));   /* n   */
    TEST_ASSERT_TRUE(utf_isprint(111));   /* o   */
    TEST_ASSERT_TRUE(utf_isprint(112));   /* p   */
    TEST_ASSERT_TRUE(utf_isprint(113));   /* q   */
    TEST_ASSERT_TRUE(utf_isprint(114));   /* r   */
    TEST_ASSERT_TRUE(utf_isprint(115));   /* s   */
    TEST_ASSERT_TRUE(utf_isprint(116));   /* t   */
    TEST_ASSERT_TRUE(utf_isprint(117));   /* u   */
    TEST_ASSERT_TRUE(utf_isprint(118));   /* v   */
    TEST_ASSERT_TRUE(utf_isprint(119));   /* w   */
    TEST_ASSERT_TRUE(utf_isprint(120));   /* x   */
    TEST_ASSERT_TRUE(utf_isprint(121));   /* y   */
    TEST_ASSERT_TRUE(utf_isprint(122));   /* z   */
    TEST_ASSERT_TRUE(utf_isprint(123));   /* {   */
    TEST_ASSERT_TRUE(utf_isprint(124));   /* |   */
    TEST_ASSERT_TRUE(utf_isprint(125));   /* }   */
    TEST_ASSERT_TRUE(utf_isprint(126));   /* ~   */
    TEST_ASSERT_FALSE(utf_isprint(127));  /* DEL */
    TEST_ASSERT_TRUE(utf_isprint(168));   /* ¨   */
    TEST_ASSERT_TRUE(utf_isprint(178));   /* ²   */
    TEST_ASSERT_FALSE(utf_isprint(2363)); /*     */
}

void test_ispunct(void)
{
    TEST_ASSERT_FALSE(utf_ispunct(0));    /* NUL */
    TEST_ASSERT_FALSE(utf_ispunct(1));    /* SOH */
    TEST_ASSERT_FALSE(utf_ispunct(2));    /* STX */
    TEST_ASSERT_FALSE(utf_ispunct(3));    /* ETX */
    TEST_ASSERT_FALSE(utf_ispunct(4));    /* EOT */
    TEST_ASSERT_FALSE(utf_ispunct(5));    /* ENQ */
    TEST_ASSERT_FALSE(utf_ispunct(6));    /* ACK */
    TEST_ASSERT_FALSE(utf_ispunct(7));    /* BEL */
    TEST_ASSERT_FALSE(utf_ispunct(8));    /* BS  */
    TEST_ASSERT_FALSE(utf_ispunct(9));    /* HT  */
    TEST_ASSERT_FALSE(utf_ispunct(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_ispunct(11));   /* VT  */
    TEST_ASSERT_FALSE(utf_ispunct(12));   /* FF  */
    TEST_ASSERT_FALSE(utf_ispunct(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_ispunct(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_ispunct(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_ispunct(14));   /* SO  */
    TEST_ASSERT_FALSE(utf_ispunct(15));   /* SI  */
    TEST_ASSERT_FALSE(utf_ispunct(16));   /* DLE */
    TEST_ASSERT_FALSE(utf_ispunct(17));   /* DC1 */
    TEST_ASSERT_FALSE(utf_ispunct(18));   /* DC2 */
    TEST_ASSERT_FALSE(utf_ispunct(19));   /* DC3 */
    TEST_ASSERT_FALSE(utf_ispunct(20));   /* DC4 */
    TEST_ASSERT_FALSE(utf_ispunct(21));   /* NAK */
    TEST_ASSERT_FALSE(utf_ispunct(22));   /* SYN */
    TEST_ASSERT_FALSE(utf_ispunct(23));   /* ETB */
    TEST_ASSERT_FALSE(utf_ispunct(24));   /* CAN */
    TEST_ASSERT_FALSE(utf_ispunct(25));   /* EM  */
    TEST_ASSERT_FALSE(utf_ispunct(26));   /* SUB */
    TEST_ASSERT_FALSE(utf_ispunct(27));   /* ESC */
    TEST_ASSERT_FALSE(utf_ispunct(28));   /* FS  */
    TEST_ASSERT_FALSE(utf_ispunct(29));   /* GS  */
    TEST_ASSERT_FALSE(utf_ispunct(30));   /* RS  */
    TEST_ASSERT_FALSE(utf_ispunct(31));   /* US  */
    TEST_ASSERT_FALSE(utf_ispunct(32));   /* SP  */
    TEST_ASSERT_TRUE(utf_ispunct(33));    /* !   */
    TEST_ASSERT_TRUE(utf_ispunct(34));    /* "   */
    TEST_ASSERT_TRUE(utf_ispunct(35));    /* #   */
    TEST_ASSERT_TRUE(utf_ispunct(36));    /* $   */
    TEST_ASSERT_TRUE(utf_ispunct(37));    /* %   */
    TEST_ASSERT_TRUE(utf_ispunct(38));    /* &   */
    TEST_ASSERT_TRUE(utf_ispunct(39));    /* '   */
    TEST_ASSERT_TRUE(utf_ispunct(40));    /* (   */
    TEST_ASSERT_TRUE(utf_ispunct(41));    /* )   */
    TEST_ASSERT_TRUE(utf_ispunct(42));    /* *   */
    TEST_ASSERT_TRUE(utf_ispunct(43));    /* +   */
    TEST_ASSERT_TRUE(utf_ispunct(44));    /* ,   */
    TEST_ASSERT_TRUE(utf_ispunct(45));    /* -   */
    TEST_ASSERT_TRUE(utf_ispunct(46));    /* .   */
    TEST_ASSERT_TRUE(utf_ispunct(47));    /* /   */
    TEST_ASSERT_FALSE(utf_ispunct(48));   /* 0   */
    TEST_ASSERT_FALSE(utf_ispunct(49));   /* 1   */
    TEST_ASSERT_FALSE(utf_ispunct(50));   /* 2   */
    TEST_ASSERT_FALSE(utf_ispunct(51));   /* 3   */
    TEST_ASSERT_FALSE(utf_ispunct(52));   /* 4   */
    TEST_ASSERT_FALSE(utf_ispunct(53));   /* 5   */
    TEST_ASSERT_FALSE(utf_ispunct(54));   /* 6   */
    TEST_ASSERT_FALSE(utf_ispunct(55));   /* 7   */
    TEST_ASSERT_FALSE(utf_ispunct(56));   /* 8   */
    TEST_ASSERT_FALSE(utf_ispunct(57));   /* 9   */
    TEST_ASSERT_TRUE(utf_ispunct(58));    /* :   */
    TEST_ASSERT_TRUE(utf_ispunct(59));    /* ;   */
    TEST_ASSERT_TRUE(utf_ispunct(60));    /* <   */
    TEST_ASSERT_TRUE(utf_ispunct(61));    /* =   */
    TEST_ASSERT_TRUE(utf_ispunct(62));    /* >   */
    TEST_ASSERT_TRUE(utf_ispunct(63));    /* ?   */
    TEST_ASSERT_TRUE(utf_ispunct(64));    /* @   */
    TEST_ASSERT_FALSE(utf_ispunct(65));   /* A   */
    TEST_ASSERT_FALSE(utf_ispunct(66));   /* B   */
    TEST_ASSERT_FALSE(utf_ispunct(67));   /* C   */
    TEST_ASSERT_FALSE(utf_ispunct(68));   /* D   */
    TEST_ASSERT_FALSE(utf_ispunct(69));   /* E   */
    TEST_ASSERT_FALSE(utf_ispunct(70));   /* F   */
    TEST_ASSERT_FALSE(utf_ispunct(71));   /* G   */
    TEST_ASSERT_FALSE(utf_ispunct(72));   /* H   */
    TEST_ASSERT_FALSE(utf_ispunct(73));   /* I   */
    TEST_ASSERT_FALSE(utf_ispunct(74));   /* J   */
    TEST_ASSERT_FALSE(utf_ispunct(75));   /* K   */
    TEST_ASSERT_FALSE(utf_ispunct(76));   /* L   */
    TEST_ASSERT_FALSE(utf_ispunct(77));   /* M   */
    TEST_ASSERT_FALSE(utf_ispunct(78));   /* N   */
    TEST_ASSERT_FALSE(utf_ispunct(79));   /* O   */
    TEST_ASSERT_FALSE(utf_ispunct(80));   /* P   */
    TEST_ASSERT_FALSE(utf_ispunct(81));   /* Q   */
    TEST_ASSERT_FALSE(utf_ispunct(82));   /* R   */
    TEST_ASSERT_FALSE(utf_ispunct(83));   /* S   */
    TEST_ASSERT_FALSE(utf_ispunct(84));   /* T   */
    TEST_ASSERT_FALSE(utf_ispunct(85));   /* U   */
    TEST_ASSERT_FALSE(utf_ispunct(86));   /* V   */
    TEST_ASSERT_FALSE(utf_ispunct(87));   /* W   */
    TEST_ASSERT_FALSE(utf_ispunct(88));   /* X   */
    TEST_ASSERT_FALSE(utf_ispunct(89));   /* Y   */
    TEST_ASSERT_FALSE(utf_ispunct(90));   /* Z   */
    TEST_ASSERT_TRUE(utf_ispunct(91));    /* [   */
    TEST_ASSERT_TRUE(utf_ispunct(92));    /* \   */
    TEST_ASSERT_TRUE(utf_ispunct(93));    /* ]   */
    TEST_ASSERT_TRUE(utf_ispunct(94));    /* ^   */
    TEST_ASSERT_TRUE(utf_ispunct(95));    /* _   */
    TEST_ASSERT_TRUE(utf_ispunct(96));    /* `   */
    TEST_ASSERT_FALSE(utf_ispunct(97));   /* a   */
    TEST_ASSERT_FALSE(utf_ispunct(98));   /* b   */
    TEST_ASSERT_FALSE(utf_ispunct(99));   /* c   */
    TEST_ASSERT_FALSE(utf_ispunct(100));  /* d   */
    TEST_ASSERT_FALSE(utf_ispunct(101));  /* e   */
    TEST_ASSERT_FALSE(utf_ispunct(102));  /* f   */
    TEST_ASSERT_FALSE(utf_ispunct(103));  /* g   */
    TEST_ASSERT_FALSE(utf_ispunct(104));  /* h   */
    TEST_ASSERT_FALSE(utf_ispunct(105));  /* i   */
    TEST_ASSERT_FALSE(utf_ispunct(106));  /* j   */
    TEST_ASSERT_FALSE(utf_ispunct(107));  /* k   */
    TEST_ASSERT_FALSE(utf_ispunct(108));  /* l   */
    TEST_ASSERT_FALSE(utf_ispunct(109));  /* m   */
    TEST_ASSERT_FALSE(utf_ispunct(110));  /* n   */
    TEST_ASSERT_FALSE(utf_ispunct(111));  /* o   */
    TEST_ASSERT_FALSE(utf_ispunct(112));  /* p   */
    TEST_ASSERT_FALSE(utf_ispunct(113));  /* q   */
    TEST_ASSERT_FALSE(utf_ispunct(114));  /* r   */
    TEST_ASSERT_FALSE(utf_ispunct(115));  /* s   */
    TEST_ASSERT_FALSE(utf_ispunct(116));  /* t   */
    TEST_ASSERT_FALSE(utf_ispunct(117));  /* u   */
    TEST_ASSERT_FALSE(utf_ispunct(118));  /* v   */
    TEST_ASSERT_FALSE(utf_ispunct(119));  /* w   */
    TEST_ASSERT_FALSE(utf_ispunct(120));  /* x   */
    TEST_ASSERT_FALSE(utf_ispunct(121));  /* y   */
    TEST_ASSERT_FALSE(utf_ispunct(122));  /* z   */
    TEST_ASSERT_TRUE(utf_ispunct(123));   /* {   */
    TEST_ASSERT_TRUE(utf_ispunct(124));   /* |   */
    TEST_ASSERT_TRUE(utf_ispunct(125));   /* }   */
    TEST_ASSERT_TRUE(utf_ispunct(126));   /* ~   */
    TEST_ASSERT_FALSE(utf_ispunct(127));  /* DEL */
    TEST_ASSERT_TRUE(utf_ispunct(161));   /* ¡   */
    TEST_ASSERT_TRUE(utf_ispunct(168));   /* ¨   */
    TEST_ASSERT_FALSE(utf_ispunct(178));  /* ²   */
    TEST_ASSERT_FALSE(utf_ispunct(2363)); /*     */
}

void test_isblank(void)
{
    TEST_ASSERT_FALSE(utf_isblank(0));     /* NUL */
    TEST_ASSERT_FALSE(utf_isblank(1));     /* SOH */
    TEST_ASSERT_FALSE(utf_isblank(2));     /* STX */
    TEST_ASSERT_FALSE(utf_isblank(3));     /* ETX */
    TEST_ASSERT_FALSE(utf_isblank(4));     /* EOT */
    TEST_ASSERT_FALSE(utf_isblank(5));     /* ENQ */
    TEST_ASSERT_FALSE(utf_isblank(6));     /* ACK */
    TEST_ASSERT_FALSE(utf_isblank(7));     /* BEL */
    TEST_ASSERT_FALSE(utf_isblank(8));     /* BS  */
    TEST_ASSERT_TRUE(utf_isblank(9));      /* HT  */
    TEST_ASSERT_FALSE(utf_isblank(10));    /* CR  */
    TEST_ASSERT_FALSE(utf_isblank(11));    /* VT  */
    TEST_ASSERT_FALSE(utf_isblank(12));    /* FF  */
    TEST_ASSERT_FALSE(utf_isblank(13));    /* LF  */
    TEST_ASSERT_FALSE(utf_isblank(14));    /* SO  */
    TEST_ASSERT_FALSE(utf_isblank(15));    /* SI  */
    TEST_ASSERT_FALSE(utf_isblank(16));    /* DLE */
    TEST_ASSERT_FALSE(utf_isblank(17));    /* DC1 */
    TEST_ASSERT_FALSE(utf_isblank(18));    /* DC2 */
    TEST_ASSERT_FALSE(utf_isblank(19));    /* DC3 */
    TEST_ASSERT_FALSE(utf_isblank(20));    /* DC4 */
    TEST_ASSERT_FALSE(utf_isblank(21));    /* NAK */
    TEST_ASSERT_FALSE(utf_isblank(22));    /* SYN */
    TEST_ASSERT_FALSE(utf_isblank(23));    /* ETB */
    TEST_ASSERT_FALSE(utf_isblank(24));    /* CAN */
    TEST_ASSERT_FALSE(utf_isblank(25));    /* EM  */
    TEST_ASSERT_FALSE(utf_isblank(26));    /* SUB */
    TEST_ASSERT_FALSE(utf_isblank(27));    /* ESC */
    TEST_ASSERT_FALSE(utf_isblank(28));    /* FS  */
    TEST_ASSERT_FALSE(utf_isblank(29));    /* GS  */
    TEST_ASSERT_FALSE(utf_isblank(30));    /* RS  */
    TEST_ASSERT_FALSE(utf_isblank(31));    /* US  */
    TEST_ASSERT_TRUE(utf_isblank(32));     /* SP  */
    TEST_ASSERT_FALSE(utf_isblank(33));    /* !   */
    TEST_ASSERT_FALSE(utf_isblank(34));    /* "   */
    TEST_ASSERT_FALSE(utf_isblank(35));    /* #   */
    TEST_ASSERT_FALSE(utf_isblank(36));    /* $   */
    TEST_ASSERT_FALSE(utf_isblank(37));    /* %   */
    TEST_ASSERT_FALSE(utf_isblank(38));    /* &   */
    TEST_ASSERT_FALSE(utf_isblank(39));    /* '   */
    TEST_ASSERT_FALSE(utf_isblank(40));    /* (   */
    TEST_ASSERT_FALSE(utf_isblank(41));    /* )   */
    TEST_ASSERT_FALSE(utf_isblank(42));    /* *   */
    TEST_ASSERT_FALSE(utf_isblank(43));    /* +   */
    TEST_ASSERT_FALSE(utf_isblank(44));    /* ,   */
    TEST_ASSERT_FALSE(utf_isblank(45));    /* -   */
    TEST_ASSERT_FALSE(utf_isblank(46));    /* .   */
    TEST_ASSERT_FALSE(utf_isblank(47));    /* /   */
    TEST_ASSERT_FALSE(utf_isblank(48));    /* 0   */
    TEST_ASSERT_FALSE(utf_isblank(49));    /* 1   */
    TEST_ASSERT_FALSE(utf_isblank(50));    /* 2   */
    TEST_ASSERT_FALSE(utf_isblank(51));    /* 3   */
    TEST_ASSERT_FALSE(utf_isblank(52));    /* 4   */
    TEST_ASSERT_FALSE(utf_isblank(53));    /* 5   */
    TEST_ASSERT_FALSE(utf_isblank(54));    /* 6   */
    TEST_ASSERT_FALSE(utf_isblank(55));    /* 7   */
    TEST_ASSERT_FALSE(utf_isblank(56));    /* 8   */
    TEST_ASSERT_FALSE(utf_isblank(57));    /* 9   */
    TEST_ASSERT_FALSE(utf_isblank(58));    /* :   */
    TEST_ASSERT_FALSE(utf_isblank(59));    /* ;   */
    TEST_ASSERT_FALSE(utf_isblank(60));    /* <   */
    TEST_ASSERT_FALSE(utf_isblank(61));    /* =   */
    TEST_ASSERT_FALSE(utf_isblank(62));    /* >   */
    TEST_ASSERT_FALSE(utf_isblank(63));    /* ?   */
    TEST_ASSERT_FALSE(utf_isblank(64));    /* @   */
    TEST_ASSERT_FALSE(utf_isblank(65));    /* A   */
    TEST_ASSERT_FALSE(utf_isblank(66));    /* B   */
    TEST_ASSERT_FALSE(utf_isblank(67));    /* C   */
    TEST_ASSERT_FALSE(utf_isblank(68));    /* D   */
    TEST_ASSERT_FALSE(utf_isblank(69));    /* E   */
    TEST_ASSERT_FALSE(utf_isblank(70));    /* F   */
    TEST_ASSERT_FALSE(utf_isblank(71));    /* G   */
    TEST_ASSERT_FALSE(utf_isblank(72));    /* H   */
    TEST_ASSERT_FALSE(utf_isblank(73));    /* I   */
    TEST_ASSERT_FALSE(utf_isblank(74));    /* J   */
    TEST_ASSERT_FALSE(utf_isblank(75));    /* K   */
    TEST_ASSERT_FALSE(utf_isblank(76));    /* L   */
    TEST_ASSERT_FALSE(utf_isblank(77));    /* M   */
    TEST_ASSERT_FALSE(utf_isblank(78));    /* N   */
    TEST_ASSERT_FALSE(utf_isblank(79));    /* O   */
    TEST_ASSERT_FALSE(utf_isblank(80));    /* P   */
    TEST_ASSERT_FALSE(utf_isblank(81));    /* Q   */
    TEST_ASSERT_FALSE(utf_isblank(82));    /* R   */
    TEST_ASSERT_FALSE(utf_isblank(83));    /* S   */
    TEST_ASSERT_FALSE(utf_isblank(84));    /* T   */
    TEST_ASSERT_FALSE(utf_isblank(85));    /* U   */
    TEST_ASSERT_FALSE(utf_isblank(86));    /* V   */
    TEST_ASSERT_FALSE(utf_isblank(87));    /* W   */
    TEST_ASSERT_FALSE(utf_isblank(88));    /* X   */
    TEST_ASSERT_FALSE(utf_isblank(89));    /* Y   */
    TEST_ASSERT_FALSE(utf_isblank(90));    /* Z   */
    TEST_ASSERT_FALSE(utf_isblank(91));    /* [   */
    TEST_ASSERT_FALSE(utf_isblank(92));    /* \   */
    TEST_ASSERT_FALSE(utf_isblank(93));    /* ]   */
    TEST_ASSERT_FALSE(utf_isblank(94));    /* ^   */
    TEST_ASSERT_FALSE(utf_isblank(95));    /* _   */
    TEST_ASSERT_FALSE(utf_isblank(96));    /* `   */
    TEST_ASSERT_FALSE(utf_isblank(97));    /* a   */
    TEST_ASSERT_FALSE(utf_isblank(98));    /* b   */
    TEST_ASSERT_FALSE(utf_isblank(99));    /* c   */
    TEST_ASSERT_FALSE(utf_isblank(100));   /* d   */
    TEST_ASSERT_FALSE(utf_isblank(101));   /* e   */
    TEST_ASSERT_FALSE(utf_isblank(102));   /* f   */
    TEST_ASSERT_FALSE(utf_isblank(103));   /* g   */
    TEST_ASSERT_FALSE(utf_isblank(104));   /* h   */
    TEST_ASSERT_FALSE(utf_isblank(105));   /* i   */
    TEST_ASSERT_FALSE(utf_isblank(106));   /* j   */
    TEST_ASSERT_FALSE(utf_isblank(107));   /* k   */
    TEST_ASSERT_FALSE(utf_isblank(108));   /* l   */
    TEST_ASSERT_FALSE(utf_isblank(109));   /* m   */
    TEST_ASSERT_FALSE(utf_isblank(110));   /* n   */
    TEST_ASSERT_FALSE(utf_isblank(111));   /* o   */
    TEST_ASSERT_FALSE(utf_isblank(112));   /* p   */
    TEST_ASSERT_FALSE(utf_isblank(113));   /* q   */
    TEST_ASSERT_FALSE(utf_isblank(114));   /* r   */
    TEST_ASSERT_FALSE(utf_isblank(115));   /* s   */
    TEST_ASSERT_FALSE(utf_isblank(116));   /* t   */
    TEST_ASSERT_FALSE(utf_isblank(117));   /* u   */
    TEST_ASSERT_FALSE(utf_isblank(118));   /* v   */
    TEST_ASSERT_FALSE(utf_isblank(119));   /* w   */
    TEST_ASSERT_FALSE(utf_isblank(120));   /* x   */
    TEST_ASSERT_FALSE(utf_isblank(121));   /* y   */
    TEST_ASSERT_FALSE(utf_isblank(122));   /* z   */
    TEST_ASSERT_FALSE(utf_isblank(123));   /* {   */
    TEST_ASSERT_FALSE(utf_isblank(124));   /* |   */
    TEST_ASSERT_FALSE(utf_isblank(125));   /* }   */
    TEST_ASSERT_FALSE(utf_isblank(126));   /* ~   */
    TEST_ASSERT_FALSE(utf_isblank(127));   /* DEL */
    TEST_ASSERT_FALSE(utf_isblank(168));   /* ¨   */
    TEST_ASSERT_FALSE(utf_isblank(178));   /* ²   */
    TEST_ASSERT_FALSE(utf_isblank(2363));  /*     */
}

void test_isspace(void)
{
    TEST_ASSERT_FALSE(utf_isspace(0));    /* NUL */
    TEST_ASSERT_FALSE(utf_isspace(1));    /* SOH */
    TEST_ASSERT_FALSE(utf_isspace(2));    /* STX */
    TEST_ASSERT_FALSE(utf_isspace(3));    /* ETX */
    TEST_ASSERT_FALSE(utf_isspace(4));    /* EOT */
    TEST_ASSERT_FALSE(utf_isspace(5));    /* ENQ */
    TEST_ASSERT_FALSE(utf_isspace(6));    /* ACK */
    TEST_ASSERT_FALSE(utf_isspace(7));    /* BEL */
    TEST_ASSERT_FALSE(utf_isspace(8));    /* BS  */
    TEST_ASSERT_TRUE(utf_isspace(9));     /* HT  */
    TEST_ASSERT_TRUE(utf_isspace(10));    /* CR  */
    TEST_ASSERT_TRUE(utf_isspace(11));    /* VT  */
    TEST_ASSERT_TRUE(utf_isspace(12));    /* FF  */
    TEST_ASSERT_TRUE(utf_isspace(13));    /* LF  */
    TEST_ASSERT_FALSE(utf_isspace(14));   /* SO  */
    TEST_ASSERT_FALSE(utf_isspace(15));   /* SI  */
    TEST_ASSERT_FALSE(utf_isspace(16));   /* DLE */
    TEST_ASSERT_FALSE(utf_isspace(17));   /* DC1 */
    TEST_ASSERT_FALSE(utf_isspace(18));   /* DC2 */
    TEST_ASSERT_FALSE(utf_isspace(19));   /* DC3 */
    TEST_ASSERT_FALSE(utf_isspace(20));   /* DC4 */
    TEST_ASSERT_FALSE(utf_isspace(21));   /* NAK */
    TEST_ASSERT_FALSE(utf_isspace(22));   /* SYN */
    TEST_ASSERT_FALSE(utf_isspace(23));   /* ETB */
    TEST_ASSERT_FALSE(utf_isspace(24));   /* CAN */
    TEST_ASSERT_FALSE(utf_isspace(25));   /* EM  */
    TEST_ASSERT_FALSE(utf_isspace(26));   /* SUB */
    TEST_ASSERT_FALSE(utf_isspace(27));   /* ESC */
    TEST_ASSERT_FALSE(utf_isspace(28));   /* FS  */
    TEST_ASSERT_FALSE(utf_isspace(29));   /* GS  */
    TEST_ASSERT_FALSE(utf_isspace(30));   /* RS  */
    TEST_ASSERT_FALSE(utf_isspace(31));   /* US  */
    TEST_ASSERT_TRUE(utf_isspace(32));    /* SP  */
    TEST_ASSERT_FALSE(utf_isspace(33));   /* !   */
    TEST_ASSERT_FALSE(utf_isspace(34));   /* "   */
    TEST_ASSERT_FALSE(utf_isspace(35));   /* #   */
    TEST_ASSERT_FALSE(utf_isspace(36));   /* $   */
    TEST_ASSERT_FALSE(utf_isspace(37));   /* %   */
    TEST_ASSERT_FALSE(utf_isspace(38));   /* &   */
    TEST_ASSERT_FALSE(utf_isspace(39));   /* '   */
    TEST_ASSERT_FALSE(utf_isspace(40));   /* (   */
    TEST_ASSERT_FALSE(utf_isspace(41));   /* )   */
    TEST_ASSERT_FALSE(utf_isspace(42));   /* *   */
    TEST_ASSERT_FALSE(utf_isspace(43));   /* +   */
    TEST_ASSERT_FALSE(utf_isspace(44));   /* ,   */
    TEST_ASSERT_FALSE(utf_isspace(45));   /* -   */
    TEST_ASSERT_FALSE(utf_isspace(46));   /* .   */
    TEST_ASSERT_FALSE(utf_isspace(47));   /* /   */
    TEST_ASSERT_FALSE(utf_isspace(48));   /* 0   */
    TEST_ASSERT_FALSE(utf_isspace(49));   /* 1   */
    TEST_ASSERT_FALSE(utf_isspace(50));   /* 2   */
    TEST_ASSERT_FALSE(utf_isspace(51));   /* 3   */
    TEST_ASSERT_FALSE(utf_isspace(52));   /* 4   */
    TEST_ASSERT_FALSE(utf_isspace(53));   /* 5   */
    TEST_ASSERT_FALSE(utf_isspace(54));   /* 6   */
    TEST_ASSERT_FALSE(utf_isspace(55));   /* 7   */
    TEST_ASSERT_FALSE(utf_isspace(56));   /* 8   */
    TEST_ASSERT_FALSE(utf_isspace(57));   /* 9   */
    TEST_ASSERT_FALSE(utf_isspace(58));   /* :   */
    TEST_ASSERT_FALSE(utf_isspace(59));   /* ;   */
    TEST_ASSERT_FALSE(utf_isspace(60));   /* <   */
    TEST_ASSERT_FALSE(utf_isspace(61));   /* =   */
    TEST_ASSERT_FALSE(utf_isspace(62));   /* >   */
    TEST_ASSERT_FALSE(utf_isspace(63));   /* ?   */
    TEST_ASSERT_FALSE(utf_isspace(64));   /* @   */
    TEST_ASSERT_FALSE(utf_isspace(65));   /* A   */
    TEST_ASSERT_FALSE(utf_isspace(66));   /* B   */
    TEST_ASSERT_FALSE(utf_isspace(67));   /* C   */
    TEST_ASSERT_FALSE(utf_isspace(68));   /* D   */
    TEST_ASSERT_FALSE(utf_isspace(69));   /* E   */
    TEST_ASSERT_FALSE(utf_isspace(70));   /* F   */
    TEST_ASSERT_FALSE(utf_isspace(71));   /* G   */
    TEST_ASSERT_FALSE(utf_isspace(72));   /* H   */
    TEST_ASSERT_FALSE(utf_isspace(73));   /* I   */
    TEST_ASSERT_FALSE(utf_isspace(74));   /* J   */
    TEST_ASSERT_FALSE(utf_isspace(75));   /* K   */
    TEST_ASSERT_FALSE(utf_isspace(76));   /* L   */
    TEST_ASSERT_FALSE(utf_isspace(77));   /* M   */
    TEST_ASSERT_FALSE(utf_isspace(78));   /* N   */
    TEST_ASSERT_FALSE(utf_isspace(79));   /* O   */
    TEST_ASSERT_FALSE(utf_isspace(80));   /* P   */
    TEST_ASSERT_FALSE(utf_isspace(81));   /* Q   */
    TEST_ASSERT_FALSE(utf_isspace(82));   /* R   */
    TEST_ASSERT_FALSE(utf_isspace(83));   /* S   */
    TEST_ASSERT_FALSE(utf_isspace(84));   /* T   */
    TEST_ASSERT_FALSE(utf_isspace(85));   /* U   */
    TEST_ASSERT_FALSE(utf_isspace(86));   /* V   */
    TEST_ASSERT_FALSE(utf_isspace(87));   /* W   */
    TEST_ASSERT_FALSE(utf_isspace(88));   /* X   */
    TEST_ASSERT_FALSE(utf_isspace(89));   /* Y   */
    TEST_ASSERT_FALSE(utf_isspace(90));   /* Z   */
    TEST_ASSERT_FALSE(utf_isspace(91));   /* [   */
    TEST_ASSERT_FALSE(utf_isspace(92));   /* \   */
    TEST_ASSERT_FALSE(utf_isspace(93));   /* ]   */
    TEST_ASSERT_FALSE(utf_isspace(94));   /* ^   */
    TEST_ASSERT_FALSE(utf_isspace(95));   /* _   */
    TEST_ASSERT_FALSE(utf_isspace(96));   /* `   */
    TEST_ASSERT_FALSE(utf_isspace(97));   /* a   */
    TEST_ASSERT_FALSE(utf_isspace(98));   /* b   */
    TEST_ASSERT_FALSE(utf_isspace(99));   /* c   */
    TEST_ASSERT_FALSE(utf_isspace(100));  /* d   */
    TEST_ASSERT_FALSE(utf_isspace(101));  /* e   */
    TEST_ASSERT_FALSE(utf_isspace(102));  /* f   */
    TEST_ASSERT_FALSE(utf_isspace(103));  /* g   */
    TEST_ASSERT_FALSE(utf_isspace(104));  /* h   */
    TEST_ASSERT_FALSE(utf_isspace(105));  /* i   */
    TEST_ASSERT_FALSE(utf_isspace(106));  /* j   */
    TEST_ASSERT_FALSE(utf_isspace(107));  /* k   */
    TEST_ASSERT_FALSE(utf_isspace(108));  /* l   */
    TEST_ASSERT_FALSE(utf_isspace(109));  /* m   */
    TEST_ASSERT_FALSE(utf_isspace(110));  /* n   */
    TEST_ASSERT_FALSE(utf_isspace(111));  /* o   */
    TEST_ASSERT_FALSE(utf_isspace(112));  /* p   */
    TEST_ASSERT_FALSE(utf_isspace(113));  /* q   */
    TEST_ASSERT_FALSE(utf_isspace(114));  /* r   */
    TEST_ASSERT_FALSE(utf_isspace(115));  /* s   */
    TEST_ASSERT_FALSE(utf_isspace(116));  /* t   */
    TEST_ASSERT_FALSE(utf_isspace(117));  /* u   */
    TEST_ASSERT_FALSE(utf_isspace(118));  /* v   */
    TEST_ASSERT_FALSE(utf_isspace(119));  /* w   */
    TEST_ASSERT_FALSE(utf_isspace(120));  /* x   */
    TEST_ASSERT_FALSE(utf_isspace(121));  /* y   */
    TEST_ASSERT_FALSE(utf_isspace(122));  /* z   */
    TEST_ASSERT_FALSE(utf_isspace(123));  /* {   */
    TEST_ASSERT_FALSE(utf_isspace(124));  /* |   */
    TEST_ASSERT_FALSE(utf_isspace(125));  /* }   */
    TEST_ASSERT_FALSE(utf_isspace(126));  /* ~   */
    TEST_ASSERT_FALSE(utf_isspace(127));  /* DEL */
    TEST_ASSERT_FALSE(utf_isspace(168));  /* ¨   */
    TEST_ASSERT_FALSE(utf_isspace(178));  /* ²   */
    TEST_ASSERT_FALSE(utf_isspace(2363)); /*     */
}

void test_isupper(void)
{
    TEST_ASSERT_FALSE(utf_isupper(0));    /* NUL */
    TEST_ASSERT_FALSE(utf_isupper(1));    /* SOH */
    TEST_ASSERT_FALSE(utf_isupper(2));    /* STX */
    TEST_ASSERT_FALSE(utf_isupper(3));    /* ETX */
    TEST_ASSERT_FALSE(utf_isupper(4));    /* EOT */
    TEST_ASSERT_FALSE(utf_isupper(5));    /* ENQ */
    TEST_ASSERT_FALSE(utf_isupper(6));    /* ACK */
    TEST_ASSERT_FALSE(utf_isupper(7));    /* BEL */
    TEST_ASSERT_FALSE(utf_isupper(8));    /* BS  */
    TEST_ASSERT_FALSE(utf_isupper(9));    /* HT  */
    TEST_ASSERT_FALSE(utf_isupper(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_isupper(11));   /* VT  */
    TEST_ASSERT_FALSE(utf_isupper(12));   /* FF  */
    TEST_ASSERT_FALSE(utf_isupper(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_isupper(14));   /* SO  */
    TEST_ASSERT_FALSE(utf_isupper(15));   /* SI  */
    TEST_ASSERT_FALSE(utf_isupper(16));   /* DLE */
    TEST_ASSERT_FALSE(utf_isupper(17));   /* DC1 */
    TEST_ASSERT_FALSE(utf_isupper(18));   /* DC2 */
    TEST_ASSERT_FALSE(utf_isupper(19));   /* DC3 */
    TEST_ASSERT_FALSE(utf_isupper(20));   /* DC4 */
    TEST_ASSERT_FALSE(utf_isupper(21));   /* NAK */
    TEST_ASSERT_FALSE(utf_isupper(22));   /* SYN */
    TEST_ASSERT_FALSE(utf_isupper(23));   /* ETB */
    TEST_ASSERT_FALSE(utf_isupper(24));   /* CAN */
    TEST_ASSERT_FALSE(utf_isupper(25));   /* EM  */
    TEST_ASSERT_FALSE(utf_isupper(26));   /* SUB */
    TEST_ASSERT_FALSE(utf_isupper(27));   /* ESC */
    TEST_ASSERT_FALSE(utf_isupper(28));   /* FS  */
    TEST_ASSERT_FALSE(utf_isupper(29));   /* GS  */
    TEST_ASSERT_FALSE(utf_isupper(30));   /* RS  */
    TEST_ASSERT_FALSE(utf_isupper(31));   /* US  */
    TEST_ASSERT_FALSE(utf_isupper(32));   /* SP  */
    TEST_ASSERT_FALSE(utf_isupper(33));   /* !   */
    TEST_ASSERT_FALSE(utf_isupper(34));   /* "   */
    TEST_ASSERT_FALSE(utf_isupper(35));   /* #   */
    TEST_ASSERT_FALSE(utf_isupper(36));   /* $   */
    TEST_ASSERT_FALSE(utf_isupper(37));   /* %   */
    TEST_ASSERT_FALSE(utf_isupper(38));   /* &   */
    TEST_ASSERT_FALSE(utf_isupper(39));   /* '   */
    TEST_ASSERT_FALSE(utf_isupper(40));   /* (   */
    TEST_ASSERT_FALSE(utf_isupper(41));   /* )   */
    TEST_ASSERT_FALSE(utf_isupper(42));   /* *   */
    TEST_ASSERT_FALSE(utf_isupper(43));   /* +   */
    TEST_ASSERT_FALSE(utf_isupper(44));   /* ,   */
    TEST_ASSERT_FALSE(utf_isupper(45));   /* -   */
    TEST_ASSERT_FALSE(utf_isupper(46));   /* .   */
    TEST_ASSERT_FALSE(utf_isupper(47));   /* /   */
    TEST_ASSERT_FALSE(utf_isupper(48));   /* 0   */
    TEST_ASSERT_FALSE(utf_isupper(49));   /* 1   */
    TEST_ASSERT_FALSE(utf_isupper(50));   /* 2   */
    TEST_ASSERT_FALSE(utf_isupper(51));   /* 3   */
    TEST_ASSERT_FALSE(utf_isupper(52));   /* 4   */
    TEST_ASSERT_FALSE(utf_isupper(53));   /* 5   */
    TEST_ASSERT_FALSE(utf_isupper(54));   /* 6   */
    TEST_ASSERT_FALSE(utf_isupper(55));   /* 7   */
    TEST_ASSERT_FALSE(utf_isupper(56));   /* 8   */
    TEST_ASSERT_FALSE(utf_isupper(57));   /* 9   */
    TEST_ASSERT_FALSE(utf_isupper(58));   /* :   */
    TEST_ASSERT_FALSE(utf_isupper(59));   /* ;   */
    TEST_ASSERT_FALSE(utf_isupper(60));   /* <   */
    TEST_ASSERT_FALSE(utf_isupper(61));   /* =   */
    TEST_ASSERT_FALSE(utf_isupper(62));   /* >   */
    TEST_ASSERT_FALSE(utf_isupper(63));   /* ?   */
    TEST_ASSERT_FALSE(utf_isupper(64));   /* @   */
    TEST_ASSERT_TRUE(utf_isupper(65));    /* A   */
    TEST_ASSERT_TRUE(utf_isupper(66));    /* B   */
    TEST_ASSERT_TRUE(utf_isupper(67));    /* C   */
    TEST_ASSERT_TRUE(utf_isupper(68));    /* D   */
    TEST_ASSERT_TRUE(utf_isupper(69));    /* E   */
    TEST_ASSERT_TRUE(utf_isupper(70));    /* F   */
    TEST_ASSERT_TRUE(utf_isupper(71));    /* G   */
    TEST_ASSERT_TRUE(utf_isupper(72));    /* H   */
    TEST_ASSERT_TRUE(utf_isupper(73));    /* I   */
    TEST_ASSERT_TRUE(utf_isupper(74));    /* J   */
    TEST_ASSERT_TRUE(utf_isupper(75));    /* K   */
    TEST_ASSERT_TRUE(utf_isupper(76));    /* L   */
    TEST_ASSERT_TRUE(utf_isupper(77));    /* M   */
    TEST_ASSERT_TRUE(utf_isupper(78));    /* N   */
    TEST_ASSERT_TRUE(utf_isupper(79));    /* O   */
    TEST_ASSERT_TRUE(utf_isupper(80));    /* P   */
    TEST_ASSERT_TRUE(utf_isupper(81));    /* Q   */
    TEST_ASSERT_TRUE(utf_isupper(82));    /* R   */
    TEST_ASSERT_TRUE(utf_isupper(83));    /* S   */
    TEST_ASSERT_TRUE(utf_isupper(84));    /* T   */
    TEST_ASSERT_TRUE(utf_isupper(85));    /* U   */
    TEST_ASSERT_TRUE(utf_isupper(86));    /* V   */
    TEST_ASSERT_TRUE(utf_isupper(87));    /* W   */
    TEST_ASSERT_TRUE(utf_isupper(88));    /* X   */
    TEST_ASSERT_TRUE(utf_isupper(89));    /* Y   */
    TEST_ASSERT_TRUE(utf_isupper(90));    /* Z   */
    TEST_ASSERT_FALSE(utf_isupper(91));   /* [   */
    TEST_ASSERT_FALSE(utf_isupper(92));   /* \   */
    TEST_ASSERT_FALSE(utf_isupper(93));   /* ]   */
    TEST_ASSERT_FALSE(utf_isupper(94));   /* ^   */
    TEST_ASSERT_FALSE(utf_isupper(95));   /* _   */
    TEST_ASSERT_FALSE(utf_isupper(96));   /* `   */
    TEST_ASSERT_FALSE(utf_isupper(97));   /* a   */
    TEST_ASSERT_FALSE(utf_isupper(98));   /* b   */
    TEST_ASSERT_FALSE(utf_isupper(99));   /* c   */
    TEST_ASSERT_FALSE(utf_isupper(100));  /* d   */
    TEST_ASSERT_FALSE(utf_isupper(101));  /* e   */
    TEST_ASSERT_FALSE(utf_isupper(102));  /* f   */
    TEST_ASSERT_FALSE(utf_isupper(103));  /* g   */
    TEST_ASSERT_FALSE(utf_isupper(104));  /* h   */
    TEST_ASSERT_FALSE(utf_isupper(105));  /* i   */
    TEST_ASSERT_FALSE(utf_isupper(106));  /* j   */
    TEST_ASSERT_FALSE(utf_isupper(107));  /* k   */
    TEST_ASSERT_FALSE(utf_isupper(108));  /* l   */
    TEST_ASSERT_FALSE(utf_isupper(109));  /* m   */
    TEST_ASSERT_FALSE(utf_isupper(110));  /* n   */
    TEST_ASSERT_FALSE(utf_isupper(111));  /* o   */
    TEST_ASSERT_FALSE(utf_isupper(112));  /* p   */
    TEST_ASSERT_FALSE(utf_isupper(113));  /* q   */
    TEST_ASSERT_FALSE(utf_isupper(114));  /* r   */
    TEST_ASSERT_FALSE(utf_isupper(115));  /* s   */
    TEST_ASSERT_FALSE(utf_isupper(116));  /* t   */
    TEST_ASSERT_FALSE(utf_isupper(117));  /* u   */
    TEST_ASSERT_FALSE(utf_isupper(118));  /* v   */
    TEST_ASSERT_FALSE(utf_isupper(119));  /* w   */
    TEST_ASSERT_FALSE(utf_isupper(120));  /* x   */
    TEST_ASSERT_FALSE(utf_isupper(121));  /* y   */
    TEST_ASSERT_FALSE(utf_isupper(122));  /* z   */
    TEST_ASSERT_FALSE(utf_isupper(123));  /* {   */
    TEST_ASSERT_FALSE(utf_isupper(124));  /* |   */
    TEST_ASSERT_FALSE(utf_isupper(125));  /* }   */
    TEST_ASSERT_FALSE(utf_isupper(126));  /* ~   */
    TEST_ASSERT_FALSE(utf_isupper(127));  /* DEL */
    TEST_ASSERT_FALSE(utf_isupper(178));  /* ²   */
}

void test_istitle(void)
{
}

void test_issymbol(void)
{
    TEST_ASSERT_TRUE(utf_issymbol(162));  /* ¢   */
    TEST_ASSERT_FALSE(utf_issymbol(161)); /* ¡   */
}

void test_iscurrency(void)
{
    TEST_ASSERT_TRUE(utf_iscurrency(162));  /* ¢   */
    TEST_ASSERT_FALSE(utf_iscurrency(161)); /* ¡   */
}

void test_ismath(void)
{
    TEST_ASSERT_FALSE(utf_ismath(178));   /* ²   */
}

void test_isxdigit(void)
{
    TEST_ASSERT_FALSE(utf_isxdigit(0));    /* NUL */
    TEST_ASSERT_FALSE(utf_isxdigit(1));    /* SOH */
    TEST_ASSERT_FALSE(utf_isxdigit(2));    /* STX */
    TEST_ASSERT_FALSE(utf_isxdigit(3));    /* ETX */
    TEST_ASSERT_FALSE(utf_isxdigit(4));    /* EOT */
    TEST_ASSERT_FALSE(utf_isxdigit(5));    /* ENQ */
    TEST_ASSERT_FALSE(utf_isxdigit(6));    /* ACK */
    TEST_ASSERT_FALSE(utf_isxdigit(7));    /* BEL */
    TEST_ASSERT_FALSE(utf_isxdigit(8));    /* BS  */
    TEST_ASSERT_FALSE(utf_isxdigit(9));    /* HT  */
    TEST_ASSERT_FALSE(utf_isxdigit(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_isxdigit(11));   /* VT  */
    TEST_ASSERT_FALSE(utf_isxdigit(12));   /* FF  */
    TEST_ASSERT_FALSE(utf_isxdigit(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_isxdigit(10));   /* CR  */
    TEST_ASSERT_FALSE(utf_isxdigit(13));   /* LF  */
    TEST_ASSERT_FALSE(utf_isxdigit(14));   /* SO  */
    TEST_ASSERT_FALSE(utf_isxdigit(15));   /* SI  */
    TEST_ASSERT_FALSE(utf_isxdigit(16));   /* DLE */
    TEST_ASSERT_FALSE(utf_isxdigit(17));   /* DC1 */
    TEST_ASSERT_FALSE(utf_isxdigit(18));   /* DC2 */
    TEST_ASSERT_FALSE(utf_isxdigit(19));   /* DC3 */
    TEST_ASSERT_FALSE(utf_isxdigit(20));   /* DC4 */
    TEST_ASSERT_FALSE(utf_isxdigit(21));   /* NAK */
    TEST_ASSERT_FALSE(utf_isxdigit(22));   /* SYN */
    TEST_ASSERT_FALSE(utf_isxdigit(23));   /* ETB */
    TEST_ASSERT_FALSE(utf_isxdigit(24));   /* CAN */
    TEST_ASSERT_FALSE(utf_isxdigit(25));   /* EM  */
    TEST_ASSERT_FALSE(utf_isxdigit(26));   /* SUB */
    TEST_ASSERT_FALSE(utf_isxdigit(27));   /* ESC */
    TEST_ASSERT_FALSE(utf_isxdigit(28));   /* FS  */
    TEST_ASSERT_FALSE(utf_isxdigit(29));   /* GS  */
    TEST_ASSERT_FALSE(utf_isxdigit(30));   /* RS  */
    TEST_ASSERT_FALSE(utf_isxdigit(31));   /* US  */
    TEST_ASSERT_FALSE(utf_isxdigit(32));   /* SP  */
    TEST_ASSERT_FALSE(utf_isxdigit(33));   /* !   */
    TEST_ASSERT_FALSE(utf_isxdigit(34));   /* "   */
    TEST_ASSERT_FALSE(utf_isxdigit(35));   /* #   */
    TEST_ASSERT_FALSE(utf_isxdigit(36));   /* $   */
    TEST_ASSERT_FALSE(utf_isxdigit(37));   /* %   */
    TEST_ASSERT_FALSE(utf_isxdigit(38));   /* &   */
    TEST_ASSERT_FALSE(utf_isxdigit(39));   /* '   */
    TEST_ASSERT_FALSE(utf_isxdigit(40));   /* (   */
    TEST_ASSERT_FALSE(utf_isxdigit(41));   /* )   */
    TEST_ASSERT_FALSE(utf_isxdigit(42));   /* *   */
    TEST_ASSERT_FALSE(utf_isxdigit(43));   /* +   */
    TEST_ASSERT_FALSE(utf_isxdigit(44));   /* ,   */
    TEST_ASSERT_FALSE(utf_isxdigit(45));   /* -   */
    TEST_ASSERT_FALSE(utf_isxdigit(46));   /* .   */
    TEST_ASSERT_FALSE(utf_isxdigit(47));   /* /   */
    TEST_ASSERT_TRUE(utf_isxdigit(48));    /* 0   */
    TEST_ASSERT_TRUE(utf_isxdigit(49));    /* 1   */
    TEST_ASSERT_TRUE(utf_isxdigit(50));    /* 2   */
    TEST_ASSERT_TRUE(utf_isxdigit(51));    /* 3   */
    TEST_ASSERT_TRUE(utf_isxdigit(52));    /* 4   */
    TEST_ASSERT_TRUE(utf_isxdigit(53));    /* 5   */
    TEST_ASSERT_TRUE(utf_isxdigit(54));    /* 6   */
    TEST_ASSERT_TRUE(utf_isxdigit(55));    /* 7   */
    TEST_ASSERT_TRUE(utf_isxdigit(56));    /* 8   */
    TEST_ASSERT_TRUE(utf_isxdigit(57));    /* 9   */
    TEST_ASSERT_FALSE(utf_isxdigit(58));   /* :   */
    TEST_ASSERT_FALSE(utf_isxdigit(59));   /* ;   */
    TEST_ASSERT_FALSE(utf_isxdigit(60));   /* <   */
    TEST_ASSERT_FALSE(utf_isxdigit(61));   /* =   */
    TEST_ASSERT_FALSE(utf_isxdigit(62));   /* >   */
    TEST_ASSERT_FALSE(utf_isxdigit(63));   /* ?   */
    TEST_ASSERT_FALSE(utf_isxdigit(64));   /* @   */
    TEST_ASSERT_TRUE(utf_isxdigit(65));    /* A   */
    TEST_ASSERT_TRUE(utf_isxdigit(66));    /* B   */
    TEST_ASSERT_TRUE(utf_isxdigit(67));    /* C   */
    TEST_ASSERT_TRUE(utf_isxdigit(68));    /* D   */
    TEST_ASSERT_TRUE(utf_isxdigit(69));    /* E   */
    TEST_ASSERT_TRUE(utf_isxdigit(70));    /* F   */
    TEST_ASSERT_FALSE(utf_isxdigit(71));   /* G   */
    TEST_ASSERT_FALSE(utf_isxdigit(72));   /* H   */
    TEST_ASSERT_FALSE(utf_isxdigit(73));   /* I   */
    TEST_ASSERT_FALSE(utf_isxdigit(74));   /* J   */
    TEST_ASSERT_FALSE(utf_isxdigit(75));   /* K   */
    TEST_ASSERT_FALSE(utf_isxdigit(76));   /* L   */
    TEST_ASSERT_FALSE(utf_isxdigit(77));   /* M   */
    TEST_ASSERT_FALSE(utf_isxdigit(78));   /* N   */
    TEST_ASSERT_FALSE(utf_isxdigit(79));   /* O   */
    TEST_ASSERT_FALSE(utf_isxdigit(80));   /* P   */
    TEST_ASSERT_FALSE(utf_isxdigit(81));   /* Q   */
    TEST_ASSERT_FALSE(utf_isxdigit(82));   /* R   */
    TEST_ASSERT_FALSE(utf_isxdigit(83));   /* S   */
    TEST_ASSERT_FALSE(utf_isxdigit(84));   /* T   */
    TEST_ASSERT_FALSE(utf_isxdigit(85));   /* U   */
    TEST_ASSERT_FALSE(utf_isxdigit(86));   /* V   */
    TEST_ASSERT_FALSE(utf_isxdigit(87));   /* W   */
    TEST_ASSERT_FALSE(utf_isxdigit(88));   /* X   */
    TEST_ASSERT_FALSE(utf_isxdigit(89));   /* Y   */
    TEST_ASSERT_FALSE(utf_isxdigit(90));   /* Z   */
    TEST_ASSERT_FALSE(utf_isxdigit(91));   /* [   */
    TEST_ASSERT_FALSE(utf_isxdigit(92));   /* \   */
    TEST_ASSERT_FALSE(utf_isxdigit(93));   /* ]   */
    TEST_ASSERT_FALSE(utf_isxdigit(94));   /* ^   */
    TEST_ASSERT_FALSE(utf_isxdigit(95));   /* _   */
    TEST_ASSERT_FALSE(utf_isxdigit(96));   /* `   */
    TEST_ASSERT_TRUE(utf_isxdigit(97));    /* a   */
    TEST_ASSERT_TRUE(utf_isxdigit(98));    /* b   */
    TEST_ASSERT_TRUE(utf_isxdigit(99));    /* c   */
    TEST_ASSERT_TRUE(utf_isxdigit(100));   /* d   */
    TEST_ASSERT_TRUE(utf_isxdigit(101));   /* e   */
    TEST_ASSERT_TRUE(utf_isxdigit(102));   /* f   */
    TEST_ASSERT_FALSE(utf_isxdigit(103));  /* g   */
    TEST_ASSERT_FALSE(utf_isxdigit(104));  /* h   */
    TEST_ASSERT_FALSE(utf_isxdigit(105));  /* i   */
    TEST_ASSERT_FALSE(utf_isxdigit(106));  /* j   */
    TEST_ASSERT_FALSE(utf_isxdigit(107));  /* k   */
    TEST_ASSERT_FALSE(utf_isxdigit(108));  /* l   */
    TEST_ASSERT_FALSE(utf_isxdigit(109));  /* m   */
    TEST_ASSERT_FALSE(utf_isxdigit(110));  /* n   */
    TEST_ASSERT_FALSE(utf_isxdigit(111));  /* o   */
    TEST_ASSERT_FALSE(utf_isxdigit(112));  /* p   */
    TEST_ASSERT_FALSE(utf_isxdigit(113));  /* q   */
    TEST_ASSERT_FALSE(utf_isxdigit(114));  /* r   */
    TEST_ASSERT_FALSE(utf_isxdigit(115));  /* s   */
    TEST_ASSERT_FALSE(utf_isxdigit(116));  /* t   */
    TEST_ASSERT_FALSE(utf_isxdigit(117));  /* u   */
    TEST_ASSERT_FALSE(utf_isxdigit(118));  /* v   */
    TEST_ASSERT_FALSE(utf_isxdigit(119));  /* w   */
    TEST_ASSERT_FALSE(utf_isxdigit(120));  /* x   */
    TEST_ASSERT_FALSE(utf_isxdigit(121));  /* y   */
    TEST_ASSERT_FALSE(utf_isxdigit(122));  /* z   */
    TEST_ASSERT_FALSE(utf_isxdigit(123));  /* {   */
    TEST_ASSERT_FALSE(utf_isxdigit(124));  /* |   */
    TEST_ASSERT_FALSE(utf_isxdigit(125));  /* }   */
    TEST_ASSERT_FALSE(utf_isxdigit(126));  /* ~   */
    TEST_ASSERT_FALSE(utf_isxdigit(127));  /* DEL */
    TEST_ASSERT_FALSE(utf_isxdigit(161));  /* ¡   */
    TEST_ASSERT_FALSE(utf_isxdigit(162));  /* ¢   */
    TEST_ASSERT_FALSE(utf_isxdigit(168));  /* ¨   */
    TEST_ASSERT_FALSE(utf_isxdigit(178));  /* ²   */
    TEST_ASSERT_FALSE(utf_isxdigit(2363)); /*     */
}

int main(void)
{
    UNITY_BEGIN();
    if (TEST_PROTECT()) {
        RUN_TEST(test_isalnum);
        RUN_TEST(test_isalpha);
        RUN_TEST(test_iscntrl);
        RUN_TEST(test_isdigit);
        RUN_TEST(test_isnumber);
        RUN_TEST(test_isinteger);
        RUN_TEST(test_isgraph);
        RUN_TEST(test_islower);
        RUN_TEST(test_isprint);
        RUN_TEST(test_ispunct);
        RUN_TEST(test_isblank);
        RUN_TEST(test_isspace);
        RUN_TEST(test_isupper);
        RUN_TEST(test_istitle);
        RUN_TEST(test_issymbol);
        RUN_TEST(test_iscurrency);
        RUN_TEST(test_ismath);
        RUN_TEST(test_isxdigit);
    }
    return UNITY_END();
}
