/*
MIT License

Copyright (c) 2022 Ryan Egesdahl

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

SPDX-FileCopyrightText: 2020 Ryan Egesdahl
SPDX-License-Identifier: MIT
*/

/* Automatically generated by bin/parse_ucd */

#ifndef UTF_UCD_H
#define UTF_UCD_H

#include <utf/utf.h>

extern const utf_rune utf_alphabetic[131756];
extern const utf_rune utf_control[65];
extern const utf_rune utf_currency[63];
extern const utf_rune utf_digit[660];
extern const utf_rune utf_graphic[450];
extern const utf_rune utf_lowercase[2227];
extern const utf_rune utf_mathematic[938];
extern const utf_rune utf_numeric[1791];
extern const utf_rune utf_printable[144532];
extern const utf_rune utf_punctuation[804];
extern const utf_rune utf_space[2002];
extern const utf_rune utf_symbol[7731];
extern const utf_rune utf_titlecase[31];
extern const utf_rune utf_uppercase[1831];

#endif /* UTF_UCD_H */

